"use client";

import { useEffect, useState } from "react";

type Row={funnel:string;offerMode:string;leads:number;entryPurchases:number;masterclassJoined:number;masterclass60m:number;workshopPurchases:number;workshopAttended:number;corePurchases:number;lostLeads:number;refundLeads:number;entryPurchaseRate:number;showUpRate:number;retention60Rate:number;leadToWorkshopRate:number;workshopAttendanceRate:number;workshopToCoreRate:number;leadToCoreRate:number;entryRevenue:number;workshopRevenue:number;coreRevenue:number;grossRevenue:number;refundValue:number;refundRate:number;netRevenue:number;revenuePerLead:number;medianLeadAgeDays:number|null;age7dPlus:number;age14dPlus:number;age30dPlus:number};
type CampaignRow=Row&{source:string;medium:string;campaign:string;campaignId:string};
type AdRow=Row&{adId:string;campaign:string;campaignId:string;source:string};
type Data={ok:true;acquisitionWindowDays:number;since:string;generatedAt:string;summary:Omit<Row,"funnel"|"offerMode">;rows:Row[];campaigns:CampaignRow[];ads:AdRow[];note:string};
function money(value:number){return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(value||0)}
function pct(value:number){return `${Number(value||0).toFixed(1)}%`}
const th={padding:"11px 12px",borderBottom:"1px solid #e2e8f0",whiteSpace:"nowrap",fontSize:11,color:"#64748b",textAlign:"left"} as const;
const td={padding:"12px",borderBottom:"1px solid #eef2f7",whiteSpace:"nowrap",fontSize:12} as const;
const card={background:"#fff",border:"1px solid #e2e8f0",borderRadius:16,padding:17} as const;
function Card({label,value,detail}:{label:string;value:string|number;detail?:string}){return <article style={card}><span style={{fontSize:10,fontWeight:900,color:"#64748b",letterSpacing:".04em"}}>{label.toUpperCase()}</span><strong style={{display:"block",fontSize:25,marginTop:7,letterSpacing:"-.03em"}}>{value}</strong>{detail?<small style={{display:"block",marginTop:6,color:"#64748b",lineHeight:1.45}}>{detail}</small>:null}</article>}
export default function FunnelCohortsPage(){
  const[days,setDays]=useState(30);const[data,setData]=useState<Data|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
  useEffect(()=>{let active=true;(async()=>{setLoading(true);setError("");try{const response=await fetch(`/api/admin/funnel-cohorts?days=${days}`);if(response.status===401){window.location.href="/admin/login";return}const body=await response.json();if(!response.ok||!body?.ok){if(active)setError(body?.error||"Unable to load cohort economics");return}if(active)setData(body)}catch(err){if(active)setError(err instanceof Error?err.message:"Unable to load cohort economics")}finally{if(active)setLoading(false)}})();return()=>{active=false}},[days]);
  const s=data?.summary;
  return <main style={{minHeight:"100vh",background:"#f6f8fb",color:"#0f172a",padding:"38px 18px 70px"}}><div style={{width:"min(1520px,100%)",margin:"0 auto"}}>
    <header style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:18,flexWrap:"wrap"}}><div><p style={{margin:0,color:"#7c3aed",fontSize:11,fontWeight:900,letterSpacing:".12em"}}>SIKHADENGE • ACQUISITION COHORT ECONOMICS</p><h1 style={{margin:"8px 0 0",fontSize:38,letterSpacing:"-.04em"}}>Lead Quality & Lifetime Revenue</h1><p style={{margin:"8px 0 0",color:"#64748b",maxWidth:930,lineHeight:1.55}}>Select leads by acquisition date, then follow those same leads through every downstream outcome available today. This answers “Which acquisition cohort produced better customers?” instead of mixing old buyers with new leads.</p></div><div style={{display:"flex",gap:10,alignItems:"end",flexWrap:"wrap"}}><a href="/admin/funnel-dashboard" style={{minHeight:40,display:"inline-flex",alignItems:"center",padding:"0 13px",border:"1px solid #cbd5e1",borderRadius:10,background:"#fff",color:"#0f172a",fontSize:11,fontWeight:900,textDecoration:"none"}}>Activity / Cash View</a><label style={{display:"grid",gap:6,fontSize:11,fontWeight:800}}>Acquisition window<select value={days} onChange={e=>setDays(Number(e.target.value))} style={{minHeight:40,border:"1px solid #d7dee8",borderRadius:10,padding:"0 12px",background:"#fff"}}><option value={7}>Last 7 days leads</option><option value={30}>Last 30 days leads</option><option value={60}>Last 60 days leads</option><option value={90}>Last 90 days leads</option><option value={180}>Last 180 days leads</option></select></label></div></header>
    {error?<div style={{marginTop:20,padding:14,borderRadius:12,background:"#fff1f2",border:"1px solid #fecaca",color:"#991b1b"}}>{error}</div>:null}{loading?<div style={{marginTop:20,padding:14,borderRadius:12,background:"#f5f3ff",border:"1px solid #ddd6fe",color:"#5b21b6"}}>Calculating cohort lifetime outcomes…</div>:null}
    <div style={{marginTop:20,padding:14,borderRadius:12,background:"#f5f3ff",border:"1px solid #ddd6fe",color:"#5b21b6",fontSize:11,lineHeight:1.6}}><strong>Two different truths:</strong> Command Center = events/cash activity occurring inside the selected calendar period. This page = leads acquired inside the selected period and their lifetime-to-date outcomes. Use activity view for operations/cash; use cohort view for lead quality, campaign quality and downstream conversion decisions.</div>
    <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(175px,1fr))",gap:12,marginTop:22}}><Card label="Cohort leads" value={s?.leads??0}/><Card label="Net cohort revenue" value={money(s?.netRevenue??0)} detail="Lifetime-to-date from selected acquired leads"/><Card label="Revenue / acquired lead" value={money(s?.revenuePerLead??0)}/><Card label="Entry purchase" value={pct(s?.entryPurchaseRate??0)} detail={`${s?.entryPurchases??0} buyers`}/><Card label="Show-up" value={pct(s?.showUpRate??0)} detail={`${s?.masterclassJoined??0} live joins`}/><Card label="Lead → workshop" value={pct(s?.leadToWorkshopRate??0)} detail={`${s?.workshopPurchases??0} workshop buyers`}/><Card label="Workshop → ₹14,999" value={pct(s?.workshopToCoreRate??0)} detail={`${s?.corePurchases??0} AI Expert buyers`}/><Card label="Lead → ₹14,999" value={pct(s?.leadToCoreRate??0)}/><Card label="Refund rate" value={pct(s?.refundRate??0)} detail={money(s?.refundValue??0)}/></section>
    <section style={{marginTop:26}}><h2 style={{margin:"0 0 6px",fontSize:20}}>Cohort maturity</h2><p style={{margin:0,color:"#64748b",fontSize:12,lineHeight:1.6}}>Recent leads have had less time to reach workshop or core conversion. Read conversion rates together with maturity—not in isolation.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12,marginTop:12}}><Card label="Median lead age" value={s?.medianLeadAgeDays==null?"—":`${s.medianLeadAgeDays.toFixed(1)} days`}/><Card label="7+ days mature" value={s?.age7dPlus??0}/><Card label="14+ days mature" value={s?.age14dPlus??0}/><Card label="30+ days mature" value={s?.age30dPlus??0}/></div></section>
    <section style={{marginTop:26,border:"1px solid #e2e8f0",borderRadius:18,overflow:"hidden",background:"#fff"}}><div style={{padding:"16px 18px",borderBottom:"1px solid #e2e8f0"}}><strong>ChatGPT / Claude × Free / Paid cohort quality</strong></div><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:1750}}><thead><tr style={{background:"#f8fafc"}}>{["Funnel","Entry","Leads","Entry %","Show-up","60m retention","Lead→WS","WS attendance","WS→Core","Lead→Core","Entry rev","Workshop rev","Core rev","Refunds","Net revenue","Revenue/lead","Median age"].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{(data?.rows||[]).map(row=><tr key={`${row.funnel}:${row.offerMode}`}><td style={{...td,fontWeight:900,textTransform:"capitalize"}}>{row.funnel}</td><td style={{...td,textTransform:"capitalize"}}>{row.offerMode}</td><td style={td}>{row.leads}</td><td style={td}>{pct(row.entryPurchaseRate)}</td><td style={td}>{pct(row.showUpRate)}</td><td style={td}>{pct(row.retention60Rate)}</td><td style={td}>{pct(row.leadToWorkshopRate)}</td><td style={td}>{pct(row.workshopAttendanceRate)}</td><td style={td}>{pct(row.workshopToCoreRate)}</td><td style={td}>{pct(row.leadToCoreRate)}</td><td style={td}>{money(row.entryRevenue)}</td><td style={td}>{money(row.workshopRevenue)}</td><td style={td}>{money(row.coreRevenue)}</td><td style={td}>{money(row.refundValue)}</td><td style={{...td,fontWeight:900}}>{money(row.netRevenue)}</td><td style={td}>{money(row.revenuePerLead)}</td><td style={td}>{row.medianLeadAgeDays==null?"—":`${row.medianLeadAgeDays.toFixed(1)}d`}</td></tr>)}</tbody></table></div></section>
    <section style={{marginTop:20,border:"1px solid #e2e8f0",borderRadius:18,overflow:"hidden",background:"#fff"}}><div style={{padding:"16px 18px",borderBottom:"1px solid #e2e8f0",display:"flex",justifyContent:"space-between",gap:10,flexWrap:"wrap"}}><div><strong>Acquisition campaign quality</strong><div style={{marginTop:4,fontSize:11,color:"#64748b"}}>Campaign attribution is taken from the original registration event, then lifetime outcomes follow the same lead ID.</div></div><span style={{padding:"6px 9px",borderRadius:999,background:"#fff7ed",color:"#9a3412",fontSize:10,fontWeight:900}}>NO SPEND = NO CPL/CAC/ROAS</span></div><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:1450}}><thead><tr style={{background:"#f8fafc"}}>{["Campaign","Source / medium","Leads","Entry","Show-up","Workshop","₹14,999","Lead→Core","Net cohort revenue","Revenue/lead","Median age","30d+ mature"].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{(data?.campaigns||[]).map((row,index)=><tr key={`${row.campaignId||row.campaign}:${index}`}><td style={{...td,fontWeight:900}}>{row.campaign}{row.campaignId?<div style={{fontSize:9,color:"#94a3b8",marginTop:3}}>{row.campaignId}</div>:null}</td><td style={td}>{row.source} / {row.medium}</td><td style={td}>{row.leads}</td><td style={td}>{row.entryPurchases}</td><td style={td}>{row.masterclassJoined}</td><td style={td}>{row.workshopPurchases}</td><td style={td}>{row.corePurchases}</td><td style={td}>{pct(row.leadToCoreRate)}</td><td style={{...td,fontWeight:900}}>{money(row.netRevenue)}</td><td style={td}>{money(row.revenuePerLead)}</td><td style={td}>{row.medianLeadAgeDays==null?"—":`${row.medianLeadAgeDays.toFixed(1)}d`}</td><td style={td}>{row.age30dPlus}</td></tr>)}</tbody></table></div></section>
    {(data?.ads||[]).length?<section style={{marginTop:20,border:"1px solid #e2e8f0",borderRadius:18,overflow:"hidden",background:"#fff"}}><div style={{padding:"16px 18px",borderBottom:"1px solid #e2e8f0"}}><strong>Ad-level customer quality</strong></div><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:1050}}><thead><tr style={{background:"#f8fafc"}}>{["Ad ID","Campaign","Leads","Workshop","₹14,999","Lead→Core","Net cohort revenue","Revenue/lead","Median age"].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{data!.ads.slice(0,25).map(row=><tr key={`${row.adId}:${row.campaignId}`}><td style={{...td,fontWeight:900}}>{row.adId}</td><td style={td}>{row.campaign}</td><td style={td}>{row.leads}</td><td style={td}>{row.workshopPurchases}</td><td style={td}>{row.corePurchases}</td><td style={td}>{pct(row.leadToCoreRate)}</td><td style={{...td,fontWeight:900}}>{money(row.netRevenue)}</td><td style={td}>{money(row.revenuePerLead)}</td><td style={td}>{row.medianLeadAgeDays==null?"—":`${row.medianLeadAgeDays.toFixed(1)}d`}</td></tr>)}</tbody></table></div></section>:null}
    <div style={{marginTop:20,padding:14,borderRadius:12,background:"#f5f3ff",border:"1px solid #ddd6fe",color:"#5b21b6",fontSize:11,lineHeight:1.65}}>{data?.note||"Waiting for cohort data…"}</div>
  </div></main>
}
