"use client";

import { useEffect, useState } from "react";

type Step = {
  messageType:string;label:string;journeyStage:string;templateName:string|null;uniqueMessages:number;uniqueLeads:number;sent:number;delivered:number;read:number;failed:number;deliveryRate:number;readRate:number;failureRate:number;medianSendDelayMinutes:number|null;sentWithinSlaRate:number;
};
type Data={ok:true;rangeDays:number;sendSlaMinutes:number;classificationCoverageRate:number;totalMessages:number;classifiedMessages:number;unclassifiedMessages:number;steps:Step[];note:string};

function pct(value:number){return `${Number(value||0).toFixed(1)}%`}
function delay(value:number|null){return value===null?"—":value<60?`${value.toFixed(1)}m`:`${(value/60).toFixed(1)}h`}
const th={padding:"11px 12px",borderBottom:"1px solid #e2e8f0",whiteSpace:"nowrap",fontSize:11,color:"#64748b",textAlign:"left"} as const;
const td={padding:"12px",borderBottom:"1px solid #eef2f7",whiteSpace:"nowrap",fontSize:12} as const;
const card={background:"#fff",border:"1px solid #e2e8f0",borderRadius:16,padding:17} as const;

export default function FunnelFollowupsPage(){
  const[days,setDays]=useState(30);const[data,setData]=useState<Data|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
  useEffect(()=>{let active=true;(async()=>{setLoading(true);setError("");try{const response=await fetch(`/api/admin/funnel-followups?days=${days}`);if(response.status===401){window.location.href="/admin/login";return}const body=await response.json();if(!response.ok||!body?.ok){if(active)setError(body?.error||"Unable to load follow-up analytics");return}if(active)setData(body)}catch(err){if(active)setError(err instanceof Error?err.message:"Unable to load follow-up analytics")}finally{if(active)setLoading(false)}})();return()=>{active=false}},[days]);
  const recommended=["registration_confirmation","reminder_24h","reminder_2h","reminder_15m","live_join_link","post_live_workshop_offer","workshop_confirmation","workshop_reminder_24h","workshop_reminder_2h","workshop_reminder_15m","advisor_followup","core_enrollment_confirmation"];
  const observed=new Set((data?.steps||[]).map(step=>step.messageType));
  return <main style={{minHeight:"100vh",background:"#f6f8fb",color:"#0f172a",padding:"38px 18px 70px"}}><div style={{width:"min(1450px,100%)",margin:"0 auto"}}>
    <header style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:18,flexWrap:"wrap"}}><div><p style={{margin:0,color:"#2563eb",fontSize:11,fontWeight:900,letterSpacing:".12em"}}>SIKHADENGE • FOLLOW-UP TELEMETRY</p><h1 style={{margin:"8px 0 0",fontSize:38,letterSpacing:"-.04em"}}>WhatsApp Follow-up Intelligence</h1><p style={{margin:"8px 0 0",color:"#64748b",maxWidth:900,lineHeight:1.55}}>Measure each reminder independently: sent → delivered → read → failed, plus scheduling delay. This prevents one blended WhatsApp percentage from hiding a weak reminder step.</p></div><div style={{display:"flex",gap:10,alignItems:"end",flexWrap:"wrap"}}><a href="/admin/funnel-dashboard" style={{minHeight:40,display:"inline-flex",alignItems:"center",padding:"0 13px",border:"1px solid #cbd5e1",borderRadius:10,background:"#fff",color:"#0f172a",fontSize:11,fontWeight:900,textDecoration:"none"}}>Command Center</a><label style={{display:"grid",gap:6,fontSize:11,fontWeight:800}}>Window<select value={days} onChange={e=>setDays(Number(e.target.value))} style={{minHeight:40,border:"1px solid #d7dee8",borderRadius:10,padding:"0 12px",background:"white"}}><option value={7}>7 days</option><option value={30}>30 days</option><option value={60}>60 days</option><option value={90}>90 days</option><option value={180}>180 days</option></select></label></div></header>
    {error?<div style={{marginTop:20,padding:14,borderRadius:12,background:"#fff1f2",border:"1px solid #fecaca",color:"#991b1b"}}>{error}</div>:null}{loading?<div style={{marginTop:20,padding:14,borderRadius:12,background:"#eff6ff",border:"1px solid #bfdbfe",color:"#1e3a8a"}}>Loading follow-up telemetry…</div>:null}
    <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12,marginTop:26}}><article style={card}><span style={{fontSize:10,fontWeight:900,color:"#64748b"}}>MESSAGES OBSERVED</span><strong style={{display:"block",marginTop:7,fontSize:26}}>{data?.totalMessages??0}</strong></article><article style={card}><span style={{fontSize:10,fontWeight:900,color:"#64748b"}}>STEP CLASSIFICATION</span><strong style={{display:"block",marginTop:7,fontSize:26}}>{pct(data?.classificationCoverageRate??0)}</strong><small style={{display:"block",marginTop:6,color:"#64748b"}}>{data?.classifiedMessages??0} classified • {data?.unclassifiedMessages??0} unclassified</small></article><article style={card}><span style={{fontSize:10,fontWeight:900,color:"#64748b"}}>SEND SLA</span><strong style={{display:"block",marginTop:7,fontSize:26}}>{data?.sendSlaMinutes??5}m</strong><small style={{display:"block",marginTop:6,color:"#64748b"}}>Configurable reminder scheduling tolerance</small></article></section>
    {(data?.classificationCoverageRate??0)<100&&data?.totalMessages?<div style={{marginTop:14,padding:14,borderRadius:12,background:"#fff7ed",border:"1px solid #fed7aa",color:"#9a3412",fontSize:11,lineHeight:1.6}}><strong>Tracking coverage is incomplete.</strong> Existing status callbacks still work, but reminder-level decisions require the agent to pass <code>messageType</code>, <code>journeyStage</code>, <code>templateName</code> and <code>scheduledFor</code>. Nothing is fabricated; missing classifications remain explicitly unclassified.</div>:null}
    <section style={{marginTop:24,border:"1px solid #e2e8f0",borderRadius:18,overflow:"hidden",background:"#fff"}}><div style={{padding:"16px 18px",borderBottom:"1px solid #e2e8f0"}}><strong>Observed message-step performance</strong></div><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:1350}}><thead><tr style={{background:"#f8fafc"}}>{["Message step","Journey","Template","Messages","Leads","Sent","Delivered","Read","Failed","Delivery","Read rate","Failure","Median send delay","Within SLA"].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{(data?.steps||[]).map((row,index)=><tr key={`${row.messageType}:${row.templateName}:${index}`}><td style={{...td,fontWeight:900,textTransform:"capitalize"}}>{row.label}</td><td style={{...td,textTransform:"capitalize"}}>{row.journeyStage}</td><td style={td}>{row.templateName||"—"}</td><td style={td}>{row.uniqueMessages}</td><td style={td}>{row.uniqueLeads}</td><td style={td}>{row.sent}</td><td style={td}>{row.delivered}</td><td style={td}>{row.read}</td><td style={td}>{row.failed}</td><td style={td}>{pct(row.deliveryRate)}</td><td style={td}>{pct(row.readRate)}</td><td style={td}>{pct(row.failureRate)}</td><td style={td}>{delay(row.medianSendDelayMinutes)}</td><td style={td}>{row.medianSendDelayMinutes===null?"—":pct(row.sentWithinSlaRate)}</td></tr>)}</tbody></table></div></section>
    <section style={{marginTop:24}}><h2 style={{margin:"0 0 6px",fontSize:20}}>Recommended tracking taxonomy</h2><p style={{margin:0,color:"#64748b",fontSize:12,lineHeight:1.6}}>These are tracking step names, not claims that every automation is already active. Green means that step has been observed in callback data.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(235px,1fr))",gap:9,marginTop:12}}>{recommended.map(step=><div key={step} style={{padding:12,borderRadius:12,border:`1px solid ${observed.has(step)?"#bbf7d0":"#e2e8f0"}`,background:observed.has(step)?"#f0fdf4":"#fff",fontSize:11,fontWeight:800,color:observed.has(step)?"#166534":"#475569"}}>{observed.has(step)?"✓ ":"○ "}{step.replaceAll("_"," ")}</div>)}</div></section>
    <div style={{marginTop:20,padding:14,borderRadius:12,background:"#eff6ff",border:"1px solid #bfdbfe",color:"#1e3a8a",fontSize:11,lineHeight:1.65}}>{data?.note||"Waiting for follow-up telemetry…"}</div>
  </div></main>
}
