"use client";
import { useEffect, useMemo, useState } from "react";

type DashboardRow = { funnel: string; offerMode: string; views: number; uniqueVisitors: number; ctaClicks: number; leads: number; leadConversionRate: number; checkoutStarts: number; purchases: number; revenue: number; };
type DashboardData = { ok: true; rangeDays: number; summary: { views: number; uniqueVisitors: number; leads: number; purchases: number; revenue: number; }; rows: DashboardRow[]; note: string; };
function money(value: number) { return new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value || 0); }

export default function FunnelDashboardPage() {
  const [days, setDays] = useState(30); const [data, setData] = useState<DashboardData | null>(null); const [error, setError] = useState("");
  useEffect(() => { let active = true; async function load() { setError(""); const response = await fetch(`/api/admin/funnel-dashboard?days=${days}`); if (response.status === 401) { window.location.href = "/admin/login"; return; } const body = await response.json(); if (!response.ok || !body?.ok) { if (active) setError(body?.error || "Unable to load dashboard"); return; } if (active) setData(body); } void load(); return () => { active = false; }; }, [days]);
  const leadRate = useMemo(() => !data?.summary.views ? 0 : (data.summary.leads / data.summary.views) * 100, [data]);
  return <main style={{ minHeight: "100vh", background: "#f6f8fb", color: "#0f172a", padding: "40px 18px" }}><div style={{ width: "min(1180px, 100%)", margin: "0 auto" }}>
    <div style={{ display: "flex", justifyContent: "space-between", gap: 20, alignItems: "end", flexWrap: "wrap" }}><div><p style={{ margin: 0, color: "#2563eb", fontSize: 12, fontWeight: 900, letterSpacing: ".12em" }}>SIKHADENGE • FUNNEL ANALYTICS</p><h1 style={{ margin: "8px 0 0", fontSize: 38, letterSpacing: "-.04em" }}>Masterclass Funnel Dashboard</h1><p style={{ margin: "8px 0 0", color: "#64748b" }}>First-party event view for ChatGPT vs Claude and Free vs Paid entry.</p></div><label style={{ display: "grid", gap: 6, fontSize: 12, fontWeight: 800 }}>Reporting window<select value={days} onChange={(event) => setDays(Number(event.target.value))} style={{ minHeight: 42, border: "1px solid #d7dee8", borderRadius: 10, padding: "0 12px", background: "white" }}><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={60}>Last 60 days</option><option value={90}>Last 90 days</option></select></label></div>
    {error ? <div style={{ marginTop: 24, padding: 16, borderRadius: 12, border: "1px solid #fecaca", background: "#fff1f2", color: "#991b1b" }}>{error}</div> : null}
    <section style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(170px, 1fr))", gap: 14, marginTop: 30 }}>{[["Offer views", data?.summary.views ?? 0],["Unique visitors", data?.summary.uniqueVisitors ?? 0],["Registrations", data?.summary.leads ?? 0],["View → lead", `${leadRate.toFixed(1)}%`],["Tracked purchases", data?.summary.purchases ?? 0],["Tracked revenue", money(data?.summary.revenue ?? 0)]].map(([label, value]) => <article key={String(label)} style={{ background: "white", border: "1px solid #e2e8f0", borderRadius: 16, padding: 20 }}><span style={{ color: "#64748b", fontSize: 12, fontWeight: 800 }}>{label}</span><strong style={{ display: "block", marginTop: 9, fontSize: 27, letterSpacing: "-.03em" }}>{value}</strong></article>)}</section>
    <section style={{ marginTop: 24, overflow: "hidden", borderRadius: 18, border: "1px solid #e2e8f0", background: "white" }}><div style={{ padding: "18px 20px", borderBottom: "1px solid #e2e8f0" }}><strong>Funnel comparison</strong></div><div style={{ overflowX: "auto" }}><table style={{ width: "100%", borderCollapse: "collapse", minWidth: 920 }}><thead><tr style={{ background: "#f8fafc", color: "#64748b", textAlign: "left", fontSize: 11 }}>{["Funnel","Entry","Views","Unique","CTA clicks","Leads","Lead CVR","Checkout","Purchases","Revenue"].map((head) => <th key={head} style={{ padding: "13px 15px", borderBottom: "1px solid #e2e8f0" }}>{head}</th>)}</tr></thead><tbody>{(data?.rows || []).map((row) => <tr key={`${row.funnel}:${row.offerMode}`} style={{ fontSize: 13 }}><td style={{ padding: 15, borderBottom: "1px solid #eef2f7", fontWeight: 900, textTransform: "capitalize" }}>{row.funnel}</td><td style={{ padding: 15, borderBottom: "1px solid #eef2f7", textTransform: "capitalize" }}>{row.offerMode}</td><td style={{ padding: 15, borderBottom: "1px solid #eef2f7" }}>{row.views}</td><td style={{ padding: 15, borderBottom: "1px solid #eef2f7" }}>{row.uniqueVisitors}</td><td style={{ padding: 15, borderBottom: "1px solid #eef2f7" }}>{row.ctaClicks}</td><td style={{ padding: 15, borderBottom: "1px solid #eef2f7" }}>{row.leads}</td><td style={{ padding: 15, borderBottom: "1px solid #eef2f7" }}>{row.leadConversionRate}%</td><td style={{ padding: 15, borderBottom: "1px solid #eef2f7" }}>{row.checkoutStarts}</td><td style={{ padding: 15, borderBottom: "1px solid #eef2f7" }}>{row.purchases}</td><td style={{ padding: 15, borderBottom: "1px solid #eef2f7" }}>{money(row.revenue)}</td></tr>)}{data && data.rows.length === 0 ? <tr><td colSpan={10} style={{ padding: 28, textAlign: "center", color: "#64748b" }}>No funnel events in this reporting window yet.</td></tr> : null}</tbody></table></div></section>
    <div style={{ marginTop: 20, borderRadius: 14, background: "#eff6ff", border: "1px solid #bfdbfe", color: "#1e3a8a", padding: 16, fontSize: 12, lineHeight: 1.6 }}>{data?.note || "Loading attribution note…"}</div>
  </div></main>;
}
