"use client";

import { useEffect, useMemo, useState } from "react";

type Followup = { unassigned:number;overdue:number;dueNext24h:number;highPriorityOpen:number;advisorPending:number;neverContacted:number };
type Bottleneck = { label:string;rate:number;from:number;to:number;drop:number } | null;
type DashboardRow = {
  funnel:string;offerMode:string;uniqueVisitors:number;views:number;ctaClicks:number;leads:number;
  whatsappSent:number;whatsappDelivered:number;whatsappRead:number;whatsappFailed:number;communityJoined:number;
  checkoutStarts:number;entryPurchases:number;masterclassJoined:number;masterclass30m:number;masterclass60m:number;masterclassOfferSeen:number;
  workshopOfferViews:number;workshopCtaClicks:number;workshopCheckoutStarts:number;workshopPurchases:number;workshopAttended:number;
  qualifiedLeads:number;workingLeads:number;coreOfferSeen:number;advisorClicks:number;coreCheckoutStarts:number;corePurchases:number;lostLeads:number;refunds:number;
  leadConversionRate:number;whatsappSendRate:number;whatsappDeliveryRate:number;whatsappReadRate:number;whatsappFailureRate:number;communityJoinFromReadRate:number;communityJoinFromLeadRate:number;
  checkoutConversionRate:number;entryCheckoutAbandonRate:number;showUpRate:number;retention30Rate:number;retention60Rate:number;liveOfferToWorkshopPageRate:number;workshopPageToCheckoutRate:number;workshopCheckoutConversionRate:number;workshopCheckoutAbandonRate:number;workshopBuyerRate:number;leadToWorkshopPurchaseRate:number;workshopAttendanceRate:number;
  advisorClickRate:number;coreOfferToCheckoutRate:number;coreCheckoutConversionRate:number;coreCheckoutAbandonRate:number;coreOfferConversionRate:number;leadToCorePurchaseRate:number;workshopBuyerToCoreRate:number;workshopAttendeeToCoreRate:number;
  entryRevenue:number;workshopRevenue:number;coreRevenue:number;grossRevenue:number;refundValue:number;refundRate:number;netRevenue:number;revenuePerLead:number;revenuePerVisitor:number;
  medianLeadToWhatsappMinutes:number|null;whatsappWithinSlaRate:number;medianLeadToWorkingMinutes:number|null;firstContactWithinSlaRate:number;medianLeadToEntryPurchaseMinutes:number|null;
  followup:Followup;bottleneck:Bottleneck;
};
type Summary = {
  uniqueVisitors:number;views:number;leads:number;whatsappSent:number;whatsappDelivered:number;whatsappRead:number;whatsappFailed:number;communityJoined:number;checkoutStarts:number;entryPurchases:number;
  masterclassJoined:number;masterclass30m:number;masterclass60m:number;masterclassOfferSeen:number;workshopOfferViews:number;workshopCheckoutStarts:number;workshopPurchases:number;workshopAttended:number;
  coreOfferSeen:number;advisorClicks:number;coreCheckoutStarts:number;corePurchases:number;lostLeads:number;refunds:number;
  entryRevenue:number;workshopRevenue:number;coreRevenue:number;grossRevenue:number;refundValue:number;refundRate:number;netRevenue:number;revenuePerLead:number;revenuePerVisitor:number;
  leadConversionRate:number;showUpRate:number;leadToWorkshopPurchaseRate:number;leadToCorePurchaseRate:number;workshopBuyerToCoreRate:number;whatsappDeliveryRate:number;whatsappReadRate:number;
  medianLeadToWhatsappMinutes:number|null;whatsappWithinSlaRate:number;medianLeadToWorkingMinutes:number|null;firstContactWithinSlaRate:number;medianLeadToEntryPurchaseMinutes:number|null;
  followup:Followup;bottleneck:Bottleneck;
};
type CampaignRow={source:string;medium:string;campaign:string;campaignId:string;visitors:number;leads:number;entryPurchases:number;workshopPurchases:number;corePurchases:number;leadConversionRate:number;leadToCorePurchaseRate:number;grossRevenue:number;refundValue:number;netRevenue:number;revenuePerLead:number;revenuePerVisitor:number};
type AdRow={adId:string;campaign:string;campaignId:string;source:string;visitors:number;leads:number;entryPurchases:number;workshopPurchases:number;corePurchases:number;leadToCorePurchaseRate:number;netRevenue:number;revenuePerLead:number};
type PaymentHealth={purpose:string;attempts:number;captured:number;failed:number;refunded:number;pending:number;amountAttempted:number;captureRate:number;failureRate:number};
type DashboardData={ok:true;rangeDays:number;generatedAt:string;sla:{firstContactMinutes:number;whatsappMinutes:number};spendConnected:boolean;summary:Summary;rows:DashboardRow[];campaigns:CampaignRow[];ads:AdRow[];paymentHealth:PaymentHealth[];topPaymentFailures:Array<{reason:string;count:number}>;note:string};

function money(value:number){return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(value||0)}
function pct(value:number){return `${Number(value||0).toFixed(1)}%`}
function minutes(value:number|null){if(value===null||!Number.isFinite(value))return "—";if(value<60)return `${value.toFixed(1)}m`;const hours=value/60;return hours<24?`${hours.toFixed(1)}h`:`${(hours/24).toFixed(1)}d`}
function purposeLabel(value:string){if(value==="masterclass_entry")return "Entry masterclass";if(value==="implementation_workshop")return "Implementation workshop";if(value==="core_program")return "AI Expert Program";return value.replaceAll("_"," ")}
const card={background:"white",border:"1px solid #e2e8f0",borderRadius:16,padding:18} as const;
const th={padding:"11px 12px",borderBottom:"1px solid #e2e8f0",whiteSpace:"nowrap",fontSize:11,color:"#64748b",textAlign:"left"} as const;
const td={padding:"12px",borderBottom:"1px solid #eef2f7",whiteSpace:"nowrap",fontSize:12} as const;
const sectionTitle={margin:"0 0 6px",fontSize:20,letterSpacing:"-.025em"} as const;
const sectionCopy={margin:0,color:"#64748b",fontSize:12,lineHeight:1.6} as const;

function MetricCard({label,value,detail,tone="default"}:{label:string;value:string|number;detail?:string;tone?:"default"|"good"|"warn"|"danger"}){
  const tones={default:{bg:"#fff",border:"#e2e8f0",value:"#0f172a"},good:{bg:"#f0fdf4",border:"#bbf7d0",value:"#166534"},warn:{bg:"#fffbeb",border:"#fde68a",value:"#92400e"},danger:{bg:"#fff1f2",border:"#fecdd3",value:"#9f1239"}}[tone];
  return <article style={{...card,background:tones.bg,borderColor:tones.border}}><span style={{color:"#64748b",fontSize:10,fontWeight:900,letterSpacing:".04em",textTransform:"uppercase"}}>{label}</span><strong style={{display:"block",marginTop:7,fontSize:25,letterSpacing:"-.035em",color:tones.value}}>{value}</strong>{detail?<span style={{display:"block",marginTop:7,color:"#64748b",fontSize:10,lineHeight:1.45}}>{detail}</span>:null}</article>
}

export default function FunnelDashboardPage(){
  const[days,setDays]=useState(30);const[data,setData]=useState<DashboardData|null>(null);const[error,setError]=useState("");const[loading,setLoading]=useState(true);
  useEffect(()=>{let active=true;(async()=>{setLoading(true);setError("");try{const r=await fetch(`/api/admin/funnel-dashboard?days=${days}`);if(r.status===401){window.location.href="/admin/login";return}const b=await r.json();if(!r.ok||!b?.ok){if(active)setError(b?.error||"Unable to load dashboard");return}if(active)setData(b)}catch(e){if(active)setError(e instanceof Error?e.message:"Unable to load dashboard")}finally{if(active)setLoading(false)}})();return()=>{active=false}},[days]);

  const rates=useMemo(()=>{const s=data?.summary;if(!s)return{community:0,retention60:0,workshopCheckout:0,coreCheckout:0};return{
    community:s.leads?(s.communityJoined/s.leads)*100:0,retention60:s.masterclassJoined?(s.masterclass60m/s.masterclassJoined)*100:0,workshopCheckout:s.workshopCheckoutStarts?(s.workshopPurchases/s.workshopCheckoutStarts)*100:0,coreCheckout:s.coreCheckoutStarts?(s.corePurchases/s.coreCheckoutStarts)*100:0,
  }},[data]);
  const s=data?.summary;

  return <main style={{minHeight:"100vh",background:"#f6f8fb",color:"#0f172a",padding:"38px 18px 70px"}}><div style={{width:"min(1540px,100%)",margin:"0 auto"}}>
    <header style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:20,flexWrap:"wrap"}}><div><p style={{margin:0,color:"#2563eb",fontSize:11,fontWeight:900,letterSpacing:".12em"}}>SIKHADENGE • REVENUE & DECISION INTELLIGENCE</p><h1 style={{margin:"8px 0 0",fontSize:40,letterSpacing:"-.045em"}}>AI Funnel Command Center</h1><p style={{margin:"8px 0 0",color:"#64748b",maxWidth:900,lineHeight:1.55}}>One decision view for ChatGPT vs Claude, Free vs Paid entry, WhatsApp follow-up, live retention, workshop monetisation, ₹14,999 enrollment, refunds and tracked net revenue.</p></div>
      <div style={{display:"flex",gap:10,alignItems:"end",flexWrap:"wrap"}}><a href="/admin/funnel-crm" style={{minHeight:40,display:"inline-flex",alignItems:"center",padding:"0 13px",border:"1px solid #cbd5e1",borderRadius:10,background:"white",color:"#0f172a",fontSize:11,fontWeight:900,textDecoration:"none"}}>Open CRM</a><label style={{display:"grid",gap:6,fontSize:11,fontWeight:800}}>Reporting window<select value={days} onChange={e=>setDays(Number(e.target.value))} style={{minHeight:40,border:"1px solid #d7dee8",borderRadius:10,padding:"0 12px",background:"white"}}><option value={7}>7 days</option><option value={30}>30 days</option><option value={60}>60 days</option><option value={90}>90 days</option><option value={180}>180 days</option></select></label></div></header>
    {error?<div style={{marginTop:22,padding:14,borderRadius:12,background:"#fff1f2",border:"1px solid #fecaca",color:"#991b1b"}}>{error}</div>:null}
    {loading?<div style={{marginTop:22,padding:14,borderRadius:12,background:"#eff6ff",border:"1px solid #bfdbfe",color:"#1e3a8a"}}>Loading decision intelligence…</div>:null}

    <section style={{marginTop:28}}><h2 style={sectionTitle}>Executive economics</h2><p style={sectionCopy}>Start here: actual tracked customer movement and revenue. No ad-spend-derived metric is shown unless spend data is verified.</p>
      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:12,marginTop:13}}>
        <MetricCard label="Net revenue" value={money(s?.netRevenue??0)} detail={`${money(s?.grossRevenue??0)} gross − ${money(s?.refundValue??0)} refunds`} tone="good"/>
        <MetricCard label="Revenue / lead" value={money(s?.revenuePerLead??0)} detail="Net tracked revenue divided by unique registrations"/>
        <MetricCard label="Revenue / visitor" value={money(s?.revenuePerVisitor??0)} detail="Useful before verified Meta spend is connected"/>
        <MetricCard label="Registrations" value={s?.leads??0} detail={`${s?.uniqueVisitors??0} globally deduplicated visitors`}/>
        <MetricCard label="Entry buyers" value={s?.entryPurchases??0} detail="Verified paid-entry purchases"/>
        <MetricCard label="Workshop buyers" value={s?.workshopPurchases??0} detail={`${pct(s?.leadToWorkshopPurchaseRate??0)} of registered leads`}/>
        <MetricCard label="₹14,999 buyers" value={s?.corePurchases??0} detail={`${pct(s?.leadToCorePurchaseRate??0)} lead → core`} tone="good"/>
        <MetricCard label="Refund rate" value={pct(s?.refundRate??0)} detail={`${s?.refunds??0} refund events • ${money(s?.refundValue??0)}`} tone={(s?.refundValue??0)>0?"warn":"default"}/>
      </div>
      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:12,marginTop:12}}>
        <MetricCard label="Entry revenue" value={money(s?.entryRevenue??0)}/><MetricCard label="Workshop revenue" value={money(s?.workshopRevenue??0)}/><MetricCard label="AI Expert revenue" value={money(s?.coreRevenue??0)}/>
      </div>
    </section>

    <section style={{marginTop:30}}><h2 style={sectionTitle}>Follow-up & response health</h2><p style={sectionCopy}>Operational leakage that the team can act on today. SLA targets are configurable; current dashboard uses {data?.sla.whatsappMinutes??5}m for WhatsApp dispatch and {data?.sla.firstContactMinutes??15}m for first human contact.</p>
      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(165px,1fr))",gap:12,marginTop:13}}>
        <MetricCard label="WA delivery" value={pct(s?.whatsappDeliveryRate??0)} detail={`${s?.whatsappDelivered??0}/${s?.whatsappSent??0} sent messages delivered`}/>
        <MetricCard label="WA read" value={pct(s?.whatsappReadRate??0)} detail={`${s?.whatsappRead??0} messages read`}/>
        <MetricCard label="Median lead → WA" value={minutes(s?.medianLeadToWhatsappMinutes??null)} detail={`${pct(s?.whatsappWithinSlaRate??0)} within ${data?.sla.whatsappMinutes??5}m SLA`}/>
        <MetricCard label="Median first contact" value={minutes(s?.medianLeadToWorkingMinutes??null)} detail={`${pct(s?.firstContactWithinSlaRate??0)} within ${data?.sla.firstContactMinutes??15}m SLA`}/>
        <MetricCard label="Unassigned" value={s?.followup.unassigned??0} detail="Open funnel leads without CRM owner" tone={(s?.followup.unassigned??0)>0?"warn":"default"}/>
        <MetricCard label="Overdue follow-ups" value={s?.followup.overdue??0} detail="Next follow-up time already passed" tone={(s?.followup.overdue??0)>0?"danger":"default"}/>
        <MetricCard label="Due next 24h" value={s?.followup.dueNext24h??0} detail="Upcoming CRM follow-up workload" tone={(s?.followup.dueNext24h??0)>0?"warn":"default"}/>
        <MetricCard label="Never contacted" value={s?.followup.neverContacted??0} detail="No human contact signal yet" tone={(s?.followup.neverContacted??0)>0?"danger":"default"}/>
        <MetricCard label="High-priority open" value={s?.followup.highPriorityOpen??0}/><MetricCard label="Advisor pending" value={s?.followup.advisorPending??0}/>
      </div>
    </section>

    <section style={{marginTop:30}}><h2 style={sectionTitle}>Conversion ladder</h2><p style={sectionCopy}>This separates acquisition, messaging, attendance and monetisation so one good top-line number cannot hide a downstream leak.</p>
      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(165px,1fr))",gap:12,marginTop:13}}>
        <MetricCard label="Visitor → lead" value={pct(s?.leadConversionRate??0)}/><MetricCard label="Community / lead" value={pct(rates.community)}/><MetricCard label="Lead → live" value={pct(s?.showUpRate??0)}/><MetricCard label="Live → 60m" value={pct(rates.retention60)}/>
        <MetricCard label="Lead → workshop" value={pct(s?.leadToWorkshopPurchaseRate??0)}/><MetricCard label="Workshop checkout CVR" value={pct(rates.workshopCheckout)}/><MetricCard label="Workshop → ₹14,999" value={pct(s?.workshopBuyerToCoreRate??0)}/><MetricCard label="Core checkout CVR" value={pct(rates.coreCheckout)}/><MetricCard label="Lead → ₹14,999" value={pct(s?.leadToCorePurchaseRate??0)} tone="good"/>
      </div>
      {s?.bottleneck?<div style={{marginTop:12,padding:16,borderRadius:14,background:"#fff7ed",border:"1px solid #fed7aa",display:"flex",justifyContent:"space-between",gap:16,flexWrap:"wrap"}}><div><strong style={{color:"#9a3412"}}>Largest observed conversion bottleneck: {s.bottleneck.label}</strong><div style={{marginTop:5,color:"#7c2d12",fontSize:11}}>{s.bottleneck.from} entered → {s.bottleneck.to} progressed • {s.bottleneck.drop} did not progress in this window.</div></div><strong style={{fontSize:24,color:"#9a3412"}}>{pct(s.bottleneck.rate)}</strong></div>:null}
    </section>

    <section style={{display:"grid",gap:16,marginTop:30}}><div><h2 style={sectionTitle}>Cohort diagnostics</h2><p style={sectionCopy}>ChatGPT/Claude and original Free/Paid acquisition remain separate through downstream revenue.</p></div>{(data?.rows||[]).map(row=><article key={`${row.funnel}:${row.offerMode}`} style={{background:"white",border:"1px solid #e2e8f0",borderRadius:20,overflow:"hidden"}}>
      <div style={{padding:"17px 19px",display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",borderBottom:"1px solid #e2e8f0"}}><div><strong style={{fontSize:18,textTransform:"capitalize"}}>{row.funnel} • {row.offerMode}</strong><div style={{marginTop:4,fontSize:11,color:"#64748b"}}>{row.uniqueVisitors} unique visitors • {money(row.netRevenue)} net • {money(row.revenuePerLead)} / lead</div></div><div style={{display:"flex",gap:7,flexWrap:"wrap"}}>{[
        `Lead ${pct(row.leadConversionRate)}`,`WA ${pct(row.whatsappDeliveryRate)}`,`Show-up ${pct(row.showUpRate)}`,`Lead→WS ${pct(row.leadToWorkshopPurchaseRate)}`,`WS→Core ${pct(row.workshopBuyerToCoreRate)}`,`Lead→Core ${pct(row.leadToCorePurchaseRate)}`
      ].map(x=><span key={x} style={{padding:"6px 9px",borderRadius:999,background:"#eff6ff",color:"#1d4ed8",fontSize:10,fontWeight:800}}>{x}</span>)}</div></div>
      <div style={{padding:18,display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(115px,1fr))",gap:9}}>{[
        ["Views",row.views],["Leads",row.leads],["WA sent",row.whatsappSent],["WA delivered",row.whatsappDelivered],["WA read",row.whatsappRead],["Community",row.communityJoined],["Entry paid",row.entryPurchases],["Live joined",row.masterclassJoined],["30m",row.masterclass30m],["60m",row.masterclass60m],["Live offer",row.masterclassOfferSeen],["Workshop page",row.workshopOfferViews],["Workshop checkout",row.workshopCheckoutStarts],["Workshop paid",row.workshopPurchases],["Workshop attended",row.workshopAttended],["Core offer",row.coreOfferSeen],["Advisor",row.advisorClicks],["Core checkout",row.coreCheckoutStarts],["Core paid",row.corePurchases],["Lost",row.lostLeads],["Refunds",row.refunds]
      ].map(([label,value])=><div key={String(label)} style={{padding:11,border:"1px solid #eef2f7",borderRadius:11,background:"#fbfdff"}}><span style={{fontSize:9,fontWeight:800,color:"#64748b"}}>{label}</span><strong style={{display:"block",marginTop:4,fontSize:19}}>{value}</strong></div>)}</div>
      <div style={{padding:"0 18px 18px",display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:9}}><div style={{padding:12,borderRadius:11,background:"#f8fafc",fontSize:11,lineHeight:1.55}}><strong>Response:</strong> WA median {minutes(row.medianLeadToWhatsappMinutes)} • Human median {minutes(row.medianLeadToWorkingMinutes)}</div><div style={{padding:12,borderRadius:11,background:"#f8fafc",fontSize:11,lineHeight:1.55}}><strong>Follow-up:</strong> {row.followup.overdue} overdue • {row.followup.unassigned} unassigned • {row.followup.neverContacted} never contacted</div><div style={{padding:12,borderRadius:11,background:row.bottleneck?"#fff7ed":"#f8fafc",fontSize:11,lineHeight:1.55}}><strong>Bottleneck:</strong> {row.bottleneck?`${row.bottleneck.label} (${pct(row.bottleneck.rate)})`:"Not enough volume yet"}</div></div>
    </article>)}</section>

    <section style={{marginTop:30,border:"1px solid #e2e8f0",borderRadius:18,overflow:"hidden",background:"white"}}><div style={{padding:"16px 18px",borderBottom:"1px solid #e2e8f0",display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><strong>Campaign decision table</strong><div style={{marginTop:4,fontSize:11,color:"#64748b"}}>Revenue and downstream buyers from captured first-party attribution.</div></div><span style={{padding:"6px 9px",borderRadius:999,background:"#fff7ed",color:"#9a3412",fontSize:10,fontWeight:900}}>SPEND NOT CONNECTED • NO FAKE CPL/CAC/ROAS</span></div><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:1450}}><thead><tr style={{background:"#f8fafc"}}>{["Campaign","Source / medium","Visitors","Leads","Lead CVR","Entry buyers","Workshop buyers","₹14,999 buyers","Lead→Core","Net revenue","Revenue / lead","Revenue / visitor"].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{(data?.campaigns||[]).map((row,index)=><tr key={`${row.campaignId||row.campaign}:${index}`}><td style={{...td,fontWeight:900}}>{row.campaign}{row.campaignId?<div style={{fontSize:9,color:"#94a3b8",marginTop:3}}>{row.campaignId}</div>:null}</td><td style={td}>{row.source} / {row.medium}</td><td style={td}>{row.visitors}</td><td style={td}>{row.leads}</td><td style={td}>{pct(row.leadConversionRate)}</td><td style={td}>{row.entryPurchases}</td><td style={td}>{row.workshopPurchases}</td><td style={td}>{row.corePurchases}</td><td style={td}>{pct(row.leadToCorePurchaseRate)}</td><td style={{...td,fontWeight:900}}>{money(row.netRevenue)}</td><td style={td}>{money(row.revenuePerLead)}</td><td style={td}>{money(row.revenuePerVisitor)}</td></tr>)}</tbody></table></div></section>

    {(data?.ads||[]).length?<section style={{marginTop:20,border:"1px solid #e2e8f0",borderRadius:18,overflow:"hidden",background:"white"}}><div style={{padding:"16px 18px",borderBottom:"1px solid #e2e8f0"}}><strong>Top attributed ads</strong><div style={{marginTop:4,fontSize:11,color:"#64748b"}}>Use this to identify which ad IDs actually create downstream buyers—not just registrations.</div></div><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:1100}}><thead><tr style={{background:"#f8fafc"}}>{["Ad ID","Campaign","Leads","Entry","Workshop","₹14,999","Lead→Core","Net revenue","Revenue / lead"].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{data!.ads.slice(0,25).map(row=><tr key={`${row.adId}:${row.campaignId}`}><td style={{...td,fontWeight:900}}>{row.adId}</td><td style={td}>{row.campaign}</td><td style={td}>{row.leads}</td><td style={td}>{row.entryPurchases}</td><td style={td}>{row.workshopPurchases}</td><td style={td}>{row.corePurchases}</td><td style={td}>{pct(row.leadToCorePurchaseRate)}</td><td style={{...td,fontWeight:900}}>{money(row.netRevenue)}</td><td style={td}>{money(row.revenuePerLead)}</td></tr>)}</tbody></table></div></section>:null}

    <section style={{marginTop:30}}><h2 style={sectionTitle}>Payment health</h2><p style={sectionCopy}>Razorpay order attempts are separated by commercial purpose so entry-payment problems cannot hide workshop or core-program checkout issues.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(245px,1fr))",gap:12,marginTop:13}}>{(data?.paymentHealth||[]).map(row=><article key={row.purpose} style={card}><strong style={{fontSize:15}}>{purposeLabel(row.purpose)}</strong><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8,marginTop:13}}><div><span style={{fontSize:9,color:"#64748b"}}>ATTEMPTS</span><b style={{display:"block",marginTop:3}}>{row.attempts}</b></div><div><span style={{fontSize:9,color:"#64748b"}}>CAPTURED</span><b style={{display:"block",marginTop:3}}>{row.captured}</b></div><div><span style={{fontSize:9,color:"#64748b"}}>FAILED</span><b style={{display:"block",marginTop:3}}>{row.failed}</b></div></div><div style={{marginTop:12,fontSize:11,color:"#475569"}}>Capture {pct(row.captureRate)} • Failure {pct(row.failureRate)} • Pending {row.pending} • Refunded {row.refunded}</div></article>)}</div>
      {(data?.topPaymentFailures||[]).length?<div style={{marginTop:12,padding:14,border:"1px solid #fecaca",background:"#fff1f2",borderRadius:12}}><strong style={{fontSize:12,color:"#991b1b"}}>Top payment failure reasons</strong><div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:9}}>{data!.topPaymentFailures.map(item=><span key={item.reason} style={{padding:"6px 9px",borderRadius:999,background:"white",border:"1px solid #fecaca",fontSize:10,color:"#7f1d1d"}}>{item.reason} • {item.count}</span>)}</div></div>:null}
    </section>

    <section style={{marginTop:30,border:"1px solid #e2e8f0",borderRadius:18,overflow:"hidden",background:"white"}}><div style={{padding:"16px 18px",borderBottom:"1px solid #e2e8f0"}}><strong>Commercial cohort comparison</strong></div><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:2300}}><thead><tr style={{background:"#f8fafc"}}>{["Funnel","Entry","Leads","Show-up","Lead→WS","Workshop paid","WS checkout CVR","WS→Core","Core offer","Advisor","Core checkout","₹14,999 paid","Core checkout CVR","Lead→Core","Entry rev","Workshop rev","Core rev","Refunds","Net revenue","Revenue/lead","Revenue/visitor","Bottleneck"].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{(data?.rows||[]).map(row=><tr key={`commercial:${row.funnel}:${row.offerMode}`}><td style={{...td,fontWeight:900,textTransform:"capitalize"}}>{row.funnel}</td><td style={{...td,textTransform:"capitalize"}}>{row.offerMode}</td><td style={td}>{row.leads}</td><td style={td}>{pct(row.showUpRate)}</td><td style={td}>{pct(row.leadToWorkshopPurchaseRate)}</td><td style={td}>{row.workshopPurchases}</td><td style={td}>{pct(row.workshopCheckoutConversionRate)}</td><td style={td}>{pct(row.workshopBuyerToCoreRate)}</td><td style={td}>{row.coreOfferSeen}</td><td style={td}>{row.advisorClicks}</td><td style={td}>{row.coreCheckoutStarts}</td><td style={td}>{row.corePurchases}</td><td style={td}>{pct(row.coreCheckoutConversionRate)}</td><td style={td}>{pct(row.leadToCorePurchaseRate)}</td><td style={td}>{money(row.entryRevenue)}</td><td style={td}>{money(row.workshopRevenue)}</td><td style={td}>{money(row.coreRevenue)}</td><td style={td}>{money(row.refundValue)}</td><td style={{...td,fontWeight:900}}>{money(row.netRevenue)}</td><td style={td}>{money(row.revenuePerLead)}</td><td style={td}>{money(row.revenuePerVisitor)}</td><td style={td}>{row.bottleneck?`${row.bottleneck.label} • ${pct(row.bottleneck.rate)}`:"—"}</td></tr>)}</tbody></table></div></section>

    <div style={{marginTop:20,padding:14,borderRadius:12,background:"#eff6ff",border:"1px solid #bfdbfe",color:"#1e3a8a",fontSize:11,lineHeight:1.65}}>{data?.note||"Loading attribution note…"}</div>
  </div></main>
}
