// Real, verifiable geographic facts for each city in KNOWN_CITIES
// (lib/generatedSkillContent.ts). State/region/tier classifications are
// standard, publicly known facts — not fabricated or invented per page.
// Tier follows the common Indian city-tier convention (Metro / Tier-1 /
// Tier-2 / Tier-3); region is the standard North/South/East/West/
// Central/Northeast grouping.

export type CityFact = {
  state: string;
  region: "North" | "South" | "East" | "West" | "Central" | "Northeast";
  tier: "Metro" | "Tier-1" | "Tier-2" | "Tier-3";
};

export const CITY_FACTS: Record<string, CityFact> = {
  agra: { state: "Uttar Pradesh", region: "North", tier: "Tier-2" },
  ahmedabad: { state: "Gujarat", region: "West", tier: "Metro" },
  ajmer: { state: "Rajasthan", region: "North", tier: "Tier-3" },
  aligarh: { state: "Uttar Pradesh", region: "North", tier: "Tier-3" },
  allahabad: { state: "Uttar Pradesh", region: "North", tier: "Tier-2" },
  ambala: { state: "Haryana", region: "North", tier: "Tier-3" },
  amritsar: { state: "Punjab", region: "North", tier: "Tier-2" },
  anand: { state: "Gujarat", region: "West", tier: "Tier-3" },
  asansol: { state: "West Bengal", region: "East", tier: "Tier-3" },
  aurangabad: { state: "Maharashtra", region: "West", tier: "Tier-2" },
  bangalore: { state: "Karnataka", region: "South", tier: "Metro" },
  bareilly: { state: "Uttar Pradesh", region: "North", tier: "Tier-3" },
  beawar: { state: "Rajasthan", region: "North", tier: "Tier-3" },
  belgaum: { state: "Karnataka", region: "South", tier: "Tier-3" },
  berhampur: { state: "Odisha", region: "East", tier: "Tier-3" },
  bhagalpur: { state: "Bihar", region: "East", tier: "Tier-3" },
  bhatinda: { state: "Punjab", region: "North", tier: "Tier-3" },
  bhilai: { state: "Chhattisgarh", region: "Central", tier: "Tier-3" },
  bhopal: { state: "Madhya Pradesh", region: "Central", tier: "Tier-1" },
  bhubaneswar: { state: "Odisha", region: "East", tier: "Tier-2" },
  bilaspur: { state: "Chhattisgarh", region: "Central", tier: "Tier-3" },
  bokaro: { state: "Jharkhand", region: "East", tier: "Tier-3" },
  calicut: { state: "Kerala", region: "South", tier: "Tier-2" },
  chandigarh: { state: "Chandigarh (UT)", region: "North", tier: "Tier-1" },
  chennai: { state: "Tamil Nadu", region: "South", tier: "Metro" },
  coimbatore: { state: "Tamil Nadu", region: "South", tier: "Tier-2" },
  cuttack: { state: "Odisha", region: "East", tier: "Tier-3" },
  darbhanga: { state: "Bihar", region: "East", tier: "Tier-3" },
  davangere: { state: "Karnataka", region: "South", tier: "Tier-3" },
  dehradun: { state: "Uttarakhand", region: "North", tier: "Tier-2" },
  delhi: { state: "Delhi (NCT)", region: "North", tier: "Metro" },
  dhanbad: { state: "Jharkhand", region: "East", tier: "Tier-2" },
  durg: { state: "Chhattisgarh", region: "Central", tier: "Tier-3" },
  durgapur: { state: "West Bengal", region: "East", tier: "Tier-3" },
  erode: { state: "Tamil Nadu", region: "South", tier: "Tier-3" },
  faizabad: { state: "Uttar Pradesh", region: "North", tier: "Tier-3" },
  faridabad: { state: "Haryana", region: "North", tier: "Tier-2" },
  firozabad: { state: "Uttar Pradesh", region: "North", tier: "Tier-3" },
  gaya: { state: "Bihar", region: "East", tier: "Tier-3" },
  ghaziabad: { state: "Uttar Pradesh", region: "North", tier: "Tier-2" },
  goa: { state: "Goa", region: "West", tier: "Tier-2" },
  gorakhpur: { state: "Uttar Pradesh", region: "North", tier: "Tier-3" },
  gurgaon: { state: "Haryana", region: "North", tier: "Tier-1" },
  guwahati: { state: "Assam", region: "Northeast", tier: "Tier-2" },
  gwalior: { state: "Madhya Pradesh", region: "Central", tier: "Tier-2" },
  haldwani: { state: "Uttarakhand", region: "North", tier: "Tier-3" },
  haridwar: { state: "Uttarakhand", region: "North", tier: "Tier-3" },
  hisar: { state: "Haryana", region: "North", tier: "Tier-3" },
  hubli: { state: "Karnataka", region: "South", tier: "Tier-3" },
  hyderabad: { state: "Telangana", region: "South", tier: "Metro" },
  indore: { state: "Madhya Pradesh", region: "Central", tier: "Tier-1" },
  jaipur: { state: "Rajasthan", region: "North", tier: "Tier-1" },
  jalandhar: { state: "Punjab", region: "North", tier: "Tier-2" },
  jalgaon: { state: "Maharashtra", region: "West", tier: "Tier-3" },
  jammu: { state: "Jammu & Kashmir (UT)", region: "North", tier: "Tier-2" },
  jamshedpur: { state: "Jharkhand", region: "East", tier: "Tier-2" },
  jhansi: { state: "Uttar Pradesh", region: "North", tier: "Tier-3" },
  kakinada: { state: "Andhra Pradesh", region: "South", tier: "Tier-3" },
  kannur: { state: "Kerala", region: "South", tier: "Tier-3" },
  kanpur: { state: "Uttar Pradesh", region: "North", tier: "Tier-1" },
  karnal: { state: "Haryana", region: "North", tier: "Tier-3" },
  kochi: { state: "Kerala", region: "South", tier: "Tier-2" },
  kolhapur: { state: "Maharashtra", region: "West", tier: "Tier-3" },
  kolkata: { state: "West Bengal", region: "East", tier: "Metro" },
  korba: { state: "Chhattisgarh", region: "Central", tier: "Tier-3" },
  kota: { state: "Rajasthan", region: "North", tier: "Tier-2" },
  kozhikode: { state: "Kerala", region: "South", tier: "Tier-2" },
  lucknow: { state: "Uttar Pradesh", region: "North", tier: "Tier-1" },
  ludhiana: { state: "Punjab", region: "North", tier: "Tier-1" },
  madurai: { state: "Tamil Nadu", region: "South", tier: "Tier-2" },
  malegaon: { state: "Maharashtra", region: "West", tier: "Tier-3" },
  mathura: { state: "Uttar Pradesh", region: "North", tier: "Tier-3" },
  meerut: { state: "Uttar Pradesh", region: "North", tier: "Tier-2" },
  mohali: { state: "Punjab", region: "North", tier: "Tier-3" },
  moradabad: { state: "Uttar Pradesh", region: "North", tier: "Tier-3" },
  mumbai: { state: "Maharashtra", region: "West", tier: "Metro" },
  muzaffarpur: { state: "Bihar", region: "East", tier: "Tier-3" },
  mysore: { state: "Karnataka", region: "South", tier: "Tier-2" },
  nagpur: { state: "Maharashtra", region: "West", tier: "Tier-1" },
  nashik: { state: "Maharashtra", region: "West", tier: "Tier-2" },
  nellore: { state: "Andhra Pradesh", region: "South", tier: "Tier-3" },
  noida: { state: "Uttar Pradesh", region: "North", tier: "Tier-1" },
  panipat: { state: "Haryana", region: "North", tier: "Tier-3" },
  pathankot: { state: "Punjab", region: "North", tier: "Tier-3" },
  patna: { state: "Bihar", region: "East", tier: "Tier-1" },
  prayagraj: { state: "Uttar Pradesh", region: "North", tier: "Tier-2" },
  pune: { state: "Maharashtra", region: "West", tier: "Metro" },
  raipur: { state: "Chhattisgarh", region: "Central", tier: "Tier-2" },
  rajkot: { state: "Gujarat", region: "West", tier: "Tier-2" },
  ranchi: { state: "Jharkhand", region: "East", tier: "Tier-2" },
  rewari: { state: "Haryana", region: "North", tier: "Tier-3" },
  rohtak: { state: "Haryana", region: "North", tier: "Tier-3" },
  rudrapur: { state: "Uttarakhand", region: "North", tier: "Tier-3" },
  satna: { state: "Madhya Pradesh", region: "Central", tier: "Tier-3" },
  shimla: { state: "Himachal Pradesh", region: "North", tier: "Tier-3" },
  siliguri: { state: "West Bengal", region: "East", tier: "Tier-3" },
  sirsa: { state: "Haryana", region: "North", tier: "Tier-3" },
  solan: { state: "Himachal Pradesh", region: "North", tier: "Tier-3" },
  sonipat: { state: "Haryana", region: "North", tier: "Tier-3" },
  surat: { state: "Gujarat", region: "West", tier: "Tier-1" },
  thane: { state: "Maharashtra", region: "West", tier: "Tier-1" },
  tirupati: { state: "Andhra Pradesh", region: "South", tier: "Tier-3" },
  trichy: { state: "Tamil Nadu", region: "South", tier: "Tier-2" },
  trivandrum: { state: "Kerala", region: "South", tier: "Tier-2" },
  udaipur: { state: "Rajasthan", region: "North", tier: "Tier-3" },
  vadodara: { state: "Gujarat", region: "West", tier: "Tier-1" },
  varanasi: { state: "Uttar Pradesh", region: "North", tier: "Tier-2" },
  vijayawada: { state: "Andhra Pradesh", region: "South", tier: "Tier-2" },
  visakhapatnam: { state: "Andhra Pradesh", region: "South", tier: "Tier-1" },
  warangal: { state: "Telangana", region: "South", tier: "Tier-3" },
  yamunanagar: { state: "Haryana", region: "North", tier: "Tier-3" },
};

export function getCityFact(citySlug: string): CityFact | null {
  return CITY_FACTS[citySlug.toLowerCase()] ?? null;
}
