// Real, genuine facts per topic family — actual tools, an accurate
// description of the practical workflow, a real common mistake, and what a
// finished piece of work looks like. Keyed by familyKey from the generated
// dataset (data/generated-seo-merged.json). Covers the top-volume families
// first (phase 3); more are added in later phases.

export type FamilyFact = {
  displayName: string;
  realTools: string[];
  coreWorkflow: string;
  commonPitfall: string;
  typicalOutput: string;
};

export const FAMILY_FACTS: Record<string, FamilyFact> = {
  "ai-marketing": {
    displayName: "AI Marketing",
    realTools: [
      "ChatGPT or Claude for campaign copy drafts",
      "Meta Ads Manager or Google Ads for execution",
      "Canva or Adobe Express for creative assets",
      "GA4 for measuring real results",
    ],
    coreWorkflow:
      "using AI to draft and iterate campaign copy or creative faster, then validating with real ad spend and analytics rather than assuming AI output performs well untested",
    commonPitfall: "publishing AI-drafted copy without checking it against brand voice, factual accuracy, or platform ad policies",
    typicalOutput: "a tested ad campaign or content calendar with documented before/after performance data",
  },
  "prompt-engineering": {
    displayName: "Prompt Engineering",
    realTools: ["ChatGPT, Claude, or Gemini directly", "A prompt and version log, even a simple spreadsheet", "The model provider's official prompting documentation"],
    coreWorkflow:
      "iterating a prompt against one specific, repeatable task, comparing outputs across versions, and documenting which changes actually improved reliability",
    commonPitfall: "treating one lucky output as proof a prompt works, without testing it across multiple runs or edge cases",
    typicalOutput: "a documented, reusable prompt template with example inputs, outputs, and known failure cases",
  },
  "ai-automation": {
    displayName: "AI Automation",
    realTools: ["Zapier, Make (Integromat), or n8n for the workflow", "The ChatGPT or Claude API for the AI step", "The specific apps being connected, such as Gmail, Sheets, or Slack"],
    coreWorkflow:
      "mapping a manual, repetitive task into a trigger-and-action workflow, inserting an AI step only where judgment or generation is genuinely needed",
    commonPitfall: "automating a process that was already broken, so the automation just fails faster and more often",
    typicalOutput: "a working automation with a documented trigger, each step, and a fallback for when it fails",
  },
  "ai-course": {
    displayName: "AI Course learning",
    realTools: ["The course platform itself", "A personal practice project kept separate from course exercises", "A notes or portfolio system to track completed work"],
    coreWorkflow: "following structured lessons but converting each one into a small applied task instead of only watching",
    commonPitfall: "completing a course end to end without ever producing an independent, undocumented piece of real work",
    typicalOutput: "a completion record plus, more importantly, two or three independent practice projects",
  },
  "ai-expert": {
    displayName: "AI Expert positioning",
    realTools: ["A documented portfolio of real AI-assisted projects", "LinkedIn or a personal site to showcase the work", "Client or employer feedback records"],
    coreWorkflow: "building visible, explainable expertise through a track record of delivered work, not a title claimed without evidence",
    commonPitfall: "calling yourself an AI expert based on course completions alone, with no demonstrated project history",
    typicalOutput: "a portfolio of three to five explained case studies showing process and outcome",
  },
  "ai-skills": {
    displayName: "AI Skills",
    realTools: ["ChatGPT, Claude, or Gemini for the specific sub-skill", "A skill-specific tool, such as Canva for design or Descript for editing", "A personal skills tracker or portfolio"],
    coreWorkflow: "picking one specific applied AI skill, not \"AI\" broadly, and building competence through repeated real tasks",
    commonPitfall: "trying to learn AI as one broad skill instead of picking a specific, applicable sub-skill first",
    typicalOutput: "demonstrated competence in one specific AI-assisted task, with before-and-after examples",
  },
  "ai-learning-path": {
    displayName: "AI Learning Path",
    realTools: ["A written personal roadmap with milestones", "Practice projects attached to each milestone", "A review source such as a mentor, community, or self-review checklist"],
    coreWorkflow: "sequencing skills from fundamentals to applied practice with checkpoints, rather than consuming content in random order",
    commonPitfall: "jumping between unrelated tutorials without a sequence, so nothing compounds into real capability",
    typicalOutput: "a completed milestone-based roadmap with a project attached to each stage",
  },
  "ai-for-design": {
    displayName: "AI for Design",
    realTools: ["Midjourney, DALL-E, or Adobe Firefly for image generation", "Canva or Figma for assembly and refinement", "Adobe Photoshop for final touch-ups"],
    coreWorkflow: "using AI for rapid concept generation, then refining manually to meet brand and quality standards before shipping",
    commonPitfall: "shipping raw AI-generated visuals without refinement, brand-fit checks, or licensing verification",
    typicalOutput: "a finished, brand-consistent design asset with the AI-assisted draft and the final refined version both documented",
  },
  "ai-side-hustle": {
    displayName: "AI Side Hustle",
    realTools: ["ChatGPT or Claude for the core deliverable", "A simple invoicing or payment tool, such as Razorpay or PayPal", "A profile on a freelance platform"],
    coreWorkflow: "packaging one specific AI-assisted deliverable, not a vague \"AI services\" offer, that a real client would actually pay for",
    commonPitfall: "marketing a vague AI side hustle with no specific service, price, or target client defined",
    typicalOutput: "one clearly scoped paid deliverable, delivered at least once, with client feedback",
  },
  "ai-business-ideas": {
    displayName: "AI Business Ideas",
    realTools: ["A one-page business model canvas", "ChatGPT or Claude for market research drafts, verified independently", "A landing page tool such as Carrd or Framer to test demand"],
    coreWorkflow: "validating demand for an AI-enabled business idea with a real, cheap test — a landing page or pre-orders — before building anything",
    commonPitfall: "building a full product around an idea before checking whether anyone will actually pay for it",
    typicalOutput: "a validated or invalidated idea backed by real evidence — signups, pre-orders, or explicit customer interest",
  },
  "ai-for-productivity": {
    displayName: "AI for Productivity",
    realTools: ["ChatGPT or Claude for drafting and summarizing", "Notion or a similar tool for the workflow system", "A calendar or task tool to measure actual time saved"],
    coreWorkflow: "applying AI to one specific recurring task and measuring the real time saved, rather than adopting tools broadly and hoping",
    commonPitfall: "adding AI tools to a workflow without removing the old manual step, so total effort doesn't actually decrease",
    typicalOutput: "one documented workflow with a measured before-and-after time comparison",
  },
  "make-money-with-ai": {
    displayName: "Making Money with AI",
    realTools: ["One specific monetizable AI skill — writing, design, automation, or similar", "A platform to find clients, such as Upwork, LinkedIn, or referrals", "A simple pricing and invoicing setup"],
    coreWorkflow: "picking one AI-assisted skill, packaging it as a specific paid service, and finding the first paying client, not a general search for income methods",
    commonPitfall: "chasing several vague income methods at once instead of committing to one skill long enough to get paid for it",
    typicalOutput: "the first paid engagement completed and documented, however small",
  },
  "ai-career": {
    displayName: "AI Career path",
    realTools: ["A resume or portfolio highlighting AI-assisted project work", "LinkedIn optimized around a specific AI-adjacent role", "Real job listings used as a specification for what to build toward"],
    coreWorkflow: "targeting one specific role or title, then reverse-engineering the skills and portfolio pieces that role actually requires",
    commonPitfall: "preparing generically for AI jobs without picking a specific role, so the portfolio doesn't match any real job listing",
    typicalOutput: "a portfolio and resume tailored to a specific job title, with at least one project matching that role's real tasks",
  },
  "ai-freelancing": {
    displayName: "AI Freelancing",
    realTools: ["A freelance platform profile, such as Upwork or Fiverr, or direct outreach", "ChatGPT or Claude for service delivery", "A contract or scope template to avoid unpaid scope creep"],
    coreWorkflow: "offering one specific AI-assisted service with a clear scope and price, then delivering it reliably for early reviews",
    commonPitfall: "listing AI services too broadly, which reads as unclear to potential clients and gets ignored",
    typicalOutput: "a completed freelance gig with a client review, however small the first one is",
  },
  "ai-for-marketing": {
    displayName: "AI for Marketing",
    realTools: ["ChatGPT or Claude for content drafts", "Canva for creative assets", "A scheduling tool such as Buffer or Later for consistent output"],
    coreWorkflow: "using AI to increase content and campaign output volume without losing consistency in brand voice or quality control",
    commonPitfall: "scaling content volume with AI faster than the review process can keep quality consistent",
    typicalOutput: "a content calendar or campaign produced faster than before, with a documented review step",
  },
  "ai-for-sales": {
    displayName: "AI for Sales",
    realTools: ["ChatGPT or Claude for outreach drafts", "A CRM such as HubSpot or Zoho to track real conversion data", "LinkedIn Sales Navigator or similar for prospecting"],
    coreWorkflow: "using AI to draft and personalize outreach at scale, then tracking real reply and conversion rates to know if it's actually working",
    commonPitfall: "sending AI-drafted outreach that reads as generic because personalization wasn't actually checked before sending",
    typicalOutput: "a tracked outreach sequence with a measured reply or conversion rate, not just volume sent",
  },
  "ai-content-creation": {
    displayName: "AI Content Creation",
    realTools: ["ChatGPT or Claude for drafts", "Canva or CapCut for visual and video assembly", "A publishing calendar to track consistency"],
    coreWorkflow: "using AI to speed up drafting, then applying a human editing pass for accuracy, voice, and originality before publishing",
    commonPitfall: "publishing AI output directly without a fact-check or editing pass, risking factual errors or generic-sounding content",
    typicalOutput: "a published piece of content with a documented before (AI draft) and after (edited) version",
  },
  "ai-video-editing": {
    displayName: "AI Video Editing",
    realTools: ["CapCut, Premiere Pro, or DaVinci Resolve for editing", "AI-assisted caption or transcription tools such as Descript", "A render and export checklist for platform specs"],
    coreWorkflow: "using AI to speed up repetitive editing tasks such as captions and rough cuts, while keeping creative decisions manual",
    commonPitfall: "relying on AI-generated captions or cuts without reviewing them, leading to timing or accuracy errors in the final export",
    typicalOutput: "a finished, published edit with the AI-assisted steps clearly identified in the workflow",
  },
  "ai-jobs": {
    displayName: "AI Jobs",
    realTools: ["Job boards filtered for AI-adjacent roles", "A portfolio matching the specific job's real requirements", "LinkedIn for direct outreach to hiring teams"],
    coreWorkflow: "matching skills to specific real job listings rather than a generic AI jobs search, and tailoring the application to that listing",
    commonPitfall: "applying broadly to AI jobs with one generic resume instead of tailoring to what each listing actually asks for",
    typicalOutput: "a small number of tailored applications with a portfolio piece matching each target role",
  },
  "ai-tools": {
    displayName: "AI Tools",
    realTools: ["The specific tool being evaluated, which varies by task", "A comparison checklist covering cost, output quality, and integration", "A trial account to test before committing"],
    coreWorkflow: "choosing a tool based on a specific task's requirements, tested with a trial, not based on hype or a single review",
    commonPitfall: "subscribing to a new AI tool every time one trends, without finishing a real task with the tools already adopted",
    typicalOutput: "one tool chosen and integrated into a real workflow, with the decision criteria documented",
  },
  chatgpt: {
    displayName: "ChatGPT",
    realTools: ["ChatGPT, via the website or app", "Custom instructions or saved prompts for repeat tasks", "OpenAI's official usage documentation"],
    coreWorkflow: "using ChatGPT for a specific, repeatable task with a refined, saved prompt rather than starting from scratch each time",
    commonPitfall: "trusting ChatGPT's factual claims without verification, especially for current events, statistics, or citations",
    typicalOutput: "a reusable prompt or workflow for one specific task, with known limitations documented",
  },
  claude: {
    displayName: "Claude",
    realTools: ["Claude, via claude.ai or the app", "Projects or custom instructions for repeat tasks", "Anthropic's official usage documentation"],
    coreWorkflow: "using Claude for tasks needing longer context or more careful reasoning, verified against the source material provided",
    commonPitfall: "assuming Claude's output about material outside the given context or documents is already verified, when it may not be",
    typicalOutput: "a reusable Claude workflow for one specific task type, with source materials attached where relevant",
  },
  gemini: {
    displayName: "Gemini",
    realTools: ["Gemini, via gemini.google.com or the app", "Google Workspace integration with Docs or Sheets where relevant", "Google's official usage documentation"],
    coreWorkflow: "using Gemini's integration with Google tools for tasks that benefit from that ecosystem, verified independently for accuracy",
    commonPitfall: "assuming tighter Google integration means higher accuracy — verification is still required regardless of the tool",
    typicalOutput: "a Gemini-assisted workflow integrated with an existing Google Workspace process",
  },
  perplexity: {
    displayName: "Perplexity",
    realTools: ["Perplexity, via perplexity.ai", "The cited sources Perplexity provides with each answer", "A separate fact-check pass on high-stakes claims"],
    coreWorkflow: "using Perplexity for research questions, then checking the cited sources directly rather than trusting the summary alone",
    commonPitfall: "treating Perplexity's summarized answer as verified fact without opening the actual cited sources",
    typicalOutput: "a research summary with source links checked and any discrepancies noted",
  },
  "nano-banana": {
    displayName: "Nano Banana image generation",
    realTools: ["The specific platform hosting the model", "A prompt library for a consistent visual style", "An image editor for final touch-ups"],
    coreWorkflow: "generating image drafts quickly, then refining prompts iteratively to match a specific visual style before final use",
    commonPitfall: "using a single generated image without iterating the prompt, missing a noticeably better result a few tries away",
    typicalOutput: "a finished image asset with the refined prompt saved for reuse",
  },
  copilot: {
    displayName: "Copilot",
    realTools: ["GitHub Copilot or Microsoft Copilot depending on context", "The IDE or app it's integrated into", "Official Microsoft and GitHub documentation"],
    coreWorkflow: "using Copilot's suggestions as a starting point that gets reviewed and adjusted, not accepted automatically",
    commonPitfall: "accepting Copilot's code or content suggestions without reviewing them for correctness or security implications",
    typicalOutput: "reviewed, working output — code or content — with a note of which suggestions were kept versus modified",
  },

  // Phase 4 — next-tier families (families #27-60 by volume)
  "canva-ai": {
    displayName: "Canva AI features",
    realTools: ["Canva Magic Studio and Magic Design", "Canva Brand Kit for consistency", "Canva's stock library or uploaded assets"],
    coreWorkflow: "using Canva's built-in AI tools to speed up templated design work, then customizing manually for brand fit",
    commonPitfall: "using default AI-generated templates without adjusting colors or fonts to match brand guidelines",
    typicalOutput: "a branded design asset — social post, presentation, or poster — exported ready for use",
  },
  cursor: {
    displayName: "Cursor (AI code editor)",
    realTools: ["Cursor IDE", "The underlying model it's connected to, such as GPT-4 or Claude", "Git for version control of AI-assisted changes"],
    coreWorkflow: "using Cursor's AI chat and autocomplete inside a real codebase, reviewing every suggested change before accepting it",
    commonPitfall: "accepting large AI-generated code changes without reading them line by line, risking bugs or security issues",
    typicalOutput: "a reviewed, working code change committed with a clear note on what the AI assisted with",
  },
  midjourney: {
    displayName: "Midjourney",
    realTools: ["Midjourney, via Discord or their web app", "A prompt library for a consistent style", "An image editor for final touch-ups"],
    coreWorkflow: "iterating prompts through multiple generations to converge on a usable image, then upscaling and editing the best result",
    commonPitfall: "using the first generated image without iterating the prompt or checking commercial usage rights",
    typicalOutput: "a finished, licensed image asset with the working prompt saved for reuse",
  },
  elevenlabs: {
    displayName: "ElevenLabs (AI voice)",
    realTools: ["ElevenLabs platform", "A script or take log to compare voice generations", "Audio editing software for final mixing"],
    coreWorkflow: "generating voice takes from a written script, comparing options, and editing the final audio for pacing and clarity",
    commonPitfall: "publishing a raw AI voice generation without listening for unnatural pacing, mispronunciations, or licensing issues",
    typicalOutput: "a finished, edited voiceover track ready for a video or audio project",
  },
  heygen: {
    displayName: "HeyGen (AI avatar video)",
    realTools: ["HeyGen platform", "A written script reviewed before generation", "Basic video editing software for final assembly"],
    coreWorkflow: "scripting content first, generating the AI avatar video from that script, then reviewing lip-sync and pacing before publishing",
    commonPitfall: "publishing an AI avatar video without checking for lip-sync errors or unnatural delivery on close review",
    typicalOutput: "a finished avatar-presented video published together with the script it was generated from",
  },
  gamma: {
    displayName: "Gamma (AI presentations)",
    realTools: ["Gamma app", "Existing brand assets such as logo and colors", "Export to PDF or PPTX for sharing"],
    coreWorkflow: "generating a first-draft deck from an outline or prompt, then manually refining slides for accuracy and brand consistency",
    commonPitfall: "presenting an AI-generated deck without checking every slide's facts and data for accuracy",
    typicalOutput: "a finished, brand-consistent presentation exported and ready to present",
  },
  "notion-ai": {
    displayName: "Notion AI",
    realTools: ["Notion AI, built into the Notion workspace", "An existing Notion workspace or database to apply it to", "A review pass on AI-generated summaries or content"],
    coreWorkflow: "using Notion AI to draft, summarize, or organize content directly inside an existing workspace structure",
    commonPitfall: "trusting AI-generated summaries of long documents without spot-checking against the source",
    typicalOutput: "a workspace page — notes, summary, or draft — reviewed and integrated into the existing system",
  },
  "leonardo-ai": {
    displayName: "Leonardo AI",
    realTools: ["Leonardo.Ai platform", "Custom-trained models where relevant", "An image editor for final touch-ups"],
    coreWorkflow: "iterating prompts and model settings to converge on a usable image, then upscaling and refining the result",
    commonPitfall: "using the first generation without adjusting settings or checking usage rights for the intended purpose",
    typicalOutput: "a finished, licensed image asset with the settings documented for reuse",
  },
  "replit-ai": {
    displayName: "Replit AI (Agent)",
    realTools: ["Replit IDE with AI features", "A running or test environment to verify output", "Git or Replit's version history for tracking changes"],
    coreWorkflow: "using Replit's AI to scaffold or complete code inside a live coding environment, testing every suggestion before relying on it",
    commonPitfall: "deploying AI-generated code from Replit without testing it in a real running environment first",
    typicalOutput: "a working, tested small application or script built and deployed from Replit",
  },
  "bolt-new": {
    displayName: "Bolt.new",
    realTools: ["Bolt.new platform", "The generated project's own build tools", "A hosting platform for deployment"],
    coreWorkflow: "describing an app in a prompt, reviewing the AI-generated scaffold, then manually refining and testing before deployment",
    commonPitfall: "deploying a Bolt-generated app without reviewing the generated code for correctness or basic security",
    typicalOutput: "a working, deployed small web app with the generated code reviewed",
  },
  suno: {
    displayName: "Suno (AI music)",
    realTools: ["Suno platform", "A lyric or style prompt drafted before generating", "Audio editing software for final mixing"],
    coreWorkflow: "drafting lyrics or a style prompt, generating multiple takes, and selecting or editing the best result",
    commonPitfall: "publishing AI-generated music without checking licensing terms for commercial use",
    typicalOutput: "a finished audio track with usage rights confirmed for its intended use",
  },
  grok: {
    displayName: "Grok",
    realTools: ["Grok, via X or the API", "xAI's official documentation", "A verification pass on real-time or current-events claims"],
    coreWorkflow: "using Grok for tasks that benefit from real-time data access, verified against primary sources for accuracy",
    commonPitfall: "trusting Grok's real-time claims without checking the underlying source, especially for fast-moving topics",
    typicalOutput: "a researched answer or draft with the real-time claims verified against a primary source",
  },
  sora: {
    displayName: "Sora (AI video generation)",
    realTools: ["Sora platform, where available", "A detailed shot-by-shot prompt", "Video editing software for final assembly"],
    coreWorkflow: "writing a detailed prompt for the desired shot, generating multiple takes, and editing the best clips together",
    commonPitfall: "using a single AI-generated clip without iterating the prompt or checking for visual artifacts",
    typicalOutput: "a finished short video clip or sequence edited from multiple generations",
  },
  runway: {
    displayName: "Runway (AI video and ML tools)",
    realTools: ["Runway ML platform", "A source video or image for editing tasks", "Traditional video editing software for final assembly"],
    coreWorkflow: "using Runway's specific tool — green screen, generation, or editing — for one task inside a larger video production pipeline",
    commonPitfall: "relying on a single Runway tool for an entire production instead of one specific task it's actually suited for",
    typicalOutput: "a finished video segment produced using Runway for one specific effect or task",
  },
  "graphic-design": {
    displayName: "Graphic Design",
    realTools: ["Adobe Photoshop, Illustrator, or Canva", "A style guide or brand kit", "Client or stakeholder feedback rounds"],
    coreWorkflow: "moving from brief to concept sketches to a refined final design, with structured feedback rounds in between",
    commonPitfall: "jumping straight to final polish without getting early feedback on the core concept",
    typicalOutput: "a finished design file plus exports in the formats the client or platform actually needs",
  },
  "web-development": {
    displayName: "Web Development",
    realTools: ["A code editor such as VS Code and a framework like React or Next.js", "Git for version control", "A hosting platform such as Vercel or Netlify for deployment"],
    coreWorkflow: "building a feature from a spec, testing it locally, then deploying and verifying it in production",
    commonPitfall: "skipping testing in a real deployed environment, so bugs only surface after real users hit them",
    typicalOutput: "a deployed, working feature or site with the code committed and documented",
  },
  "online-business": {
    displayName: "Online Business",
    realTools: ["A storefront platform such as Shopify or WordPress", "A payment processor such as Razorpay or Stripe", "Basic analytics to track real traffic and conversions"],
    coreWorkflow: "validating one specific offer with real traffic and payment data before investing in scaling it",
    commonPitfall: "building out a full online business before validating that anyone will actually buy the core offer",
    typicalOutput: "a live storefront or offer page with real traffic and at least one real transaction recorded",
  },
  consulting: {
    displayName: "Consulting",
    realTools: ["A clearly scoped service offering document", "A portfolio of past client outcomes", "A proposal or contract template"],
    coreWorkflow: "packaging expertise into one specific, sellable service, then pitching it to a defined target client with proof of past results",
    commonPitfall: "offering vague, broad consulting services instead of one specific, provable capability",
    typicalOutput: "a signed engagement or proposal with a clearly scoped deliverable and price",
  },
  "video-editing": {
    displayName: "Video Editing",
    realTools: ["Premiere Pro, DaVinci Resolve, or CapCut", "A structured project and asset organization system", "A platform-specific export checklist"],
    coreWorkflow: "assembling a rough cut from raw footage, refining pacing and audio, then exporting to the target platform's specs",
    commonPitfall: "skipping a proper rough-cut review before investing time in fine polish that might get cut anyway",
    typicalOutput: "a finished, exported edit matching the target platform's format and length requirements",
  },
  "digital-marketing": {
    displayName: "Digital Marketing",
    realTools: ["Google Ads or Meta Ads Manager", "GA4 for tracking", "An email or CRM tool such as Mailchimp or HubSpot"],
    coreWorkflow: "running a small, measured campaign, tracking real conversion data, and iterating based on results rather than assumptions",
    commonPitfall: "launching a campaign without a tracking setup, leaving no real data to learn from afterward",
    typicalOutput: "a completed campaign with a documented result — cost per lead, conversion rate, or similar real metric",
  },
  copywriting: {
    displayName: "Copywriting",
    realTools: ["A swipe file of real examples in the target category", "A structured brief template", "A/B testing where the platform supports it"],
    coreWorkflow: "writing from a clear brief covering audience, goal, and offer, then testing or getting feedback before finalizing",
    commonPitfall: "writing copy without a clear brief, producing something polished but not aligned with the actual goal",
    typicalOutput: "a finished piece of copy — ad, landing page, or email — tied to a measurable goal",
  },
  "personal-branding": {
    displayName: "Personal Branding",
    realTools: ["LinkedIn or another platform matching the target audience", "A content calendar for consistency", "A portfolio or case-study page"],
    coreWorkflow: "publishing consistently around one clear area of expertise, backed by real work examples, not just opinions",
    commonPitfall: "posting inconsistently about too many unrelated topics, which prevents any clear expertise from forming",
    typicalOutput: "a recognizable, focused profile or presence with a documented body of related work",
  },
  freelancing: {
    displayName: "Freelancing",
    realTools: ["A freelance platform profile or a direct outreach system", "A contract and scope template", "An invoicing and payment setup"],
    coreWorkflow: "defining one clear, sellable service, pricing it, and delivering the first paid engagement reliably",
    commonPitfall: "offering too many different services at once instead of one clear, specific offer clients can understand quickly",
    typicalOutput: "a completed paid engagement with a client review or referral",
  },
  "ai-for-creators": {
    displayName: "AI for Creators",
    realTools: ["ChatGPT or Claude for scripting and ideas", "Canva or CapCut for asset production", "A content calendar for consistency"],
    coreWorkflow: "using AI to speed up ideation and production while keeping the creative voice and final edit decisions manual",
    commonPitfall: "letting AI-generated ideas or scripts replace the creator's own voice, making content feel generic",
    typicalOutput: "a published piece of content that used AI for speed but retained the creator's distinct voice",
  },
  python: {
    displayName: "Python",
    realTools: ["Python itself, via python.org or Anaconda", "VS Code or PyCharm as an editor", "pip for installing the real libraries needed for the task"],
    coreWorkflow: "writing and testing small scripts against a real task, building up to larger programs incrementally",
    commonPitfall: "learning syntax through tutorials without writing any original scripts solving a real problem",
    typicalOutput: "a working script or small program solving one real, defined problem",
  },
  sales: {
    displayName: "Sales",
    realTools: ["A CRM such as HubSpot or Zoho, or a spreadsheet at minimum", "A defined outreach or follow-up sequence", "Call or meeting notes to track real objections"],
    coreWorkflow: "running a defined outreach sequence, tracking real response and conversion data, and refining based on actual objections heard",
    commonPitfall: "having no tracking system, so the same objections and mistakes repeat without being noticed",
    typicalOutput: "a tracked sales sequence with a measured conversion rate and documented common objections",
  },
  seo: {
    displayName: "SEO",
    realTools: ["Google Search Console", "A keyword research tool such as Ahrefs, Semrush, or Google's own tools", "Google Analytics (GA4) for tracking real traffic"],
    coreWorkflow: "targeting one specific keyword or intent, publishing genuinely useful content for it, then tracking real rankings and traffic over weeks",
    commonPitfall: "expecting ranking results within days, when realistic SEO timelines are measured in weeks to months",
    typicalOutput: "a published page targeting one clear intent, with tracked ranking and traffic data over time",
  },
  "no-code-development": {
    displayName: "No-Code Development",
    realTools: ["A no-code platform matching the task, such as Bubble, Webflow, or Glide", "The platform's own template library as a starting point", "A hosting or publish step specific to that platform"],
    coreWorkflow: "building a working prototype using platform templates first, then customizing only what's necessary for the specific use case",
    commonPitfall: "trying to build a fully custom solution from scratch instead of starting from the platform's existing templates",
    typicalOutput: "a working, published no-code app or site solving one specific real use case",
  },
  "motion-graphics": {
    displayName: "Motion Graphics",
    realTools: ["Adobe After Effects", "A storyboard or animatic before full production", "A render and export checklist for the target platform"],
    coreWorkflow: "storyboarding the motion first, building it in stages from rough animation to polish, and exporting to platform specs",
    commonPitfall: "jumping straight into detailed animation without a storyboard, leading to reworked timing later",
    typicalOutput: "a finished, exported motion graphics piece matching the target platform's specs",
  },
  "after-effects": {
    displayName: "After Effects",
    realTools: ["Adobe After Effects", "Plugins relevant to the task, such as particle or text plugins", "A render queue and export checklist"],
    coreWorkflow: "building an effect or animation in layered stages, previewing at low resolution before committing to a full render",
    commonPitfall: "working at full render quality throughout, wasting time on iterations that should be previewed at lower quality first",
    typicalOutput: "a finished, exported effect or animation ready for the target video project",
  },
  "premiere-pro": {
    displayName: "Premiere Pro",
    realTools: ["Adobe Premiere Pro", "Organized bins and project structure for footage", "Adobe Media Encoder for export"],
    coreWorkflow: "organizing footage first, building a rough cut, then refining audio and color before final export",
    commonPitfall: "skipping footage organization, which makes editing slower and more error-prone as the project grows",
    typicalOutput: "a finished, exported edit with organized project files for future reuse",
  },
  "logo-design": {
    displayName: "Logo Design",
    realTools: ["Adobe Illustrator for vector work", "A mood board or brand brief", "Client feedback rounds on concepts before final delivery"],
    coreWorkflow: "starting from a brief and mood board, sketching multiple concepts, then refining the strongest one into a final vector logo",
    commonPitfall: "presenting only one polished concept instead of a few distinct directions for the client to react to",
    typicalOutput: "a finished vector logo file delivered in the formats and color variants the client needs",
  },
  "ui-design": {
    displayName: "UI Design",
    realTools: ["Figma", "A design system or component library", "Real usability feedback from testing"],
    coreWorkflow: "designing from a wireframe to a high-fidelity screen, checked against an existing design system for consistency",
    commonPitfall: "designing screens that look good in isolation but ignore the existing design system, creating inconsistency",
    typicalOutput: "a finished, consistent screen design ready to hand off to development",
  },
  "ux-design": {
    displayName: "UX Design",
    realTools: ["Figma for wireframes and prototypes", "A user research method such as interviews or surveys", "A usability testing process, even an informal one"],
    coreWorkflow: "researching real user needs first, then wireframing and testing before any visual design happens",
    commonPitfall: "skipping user research and jumping straight to wireframes based on assumptions",
    typicalOutput: "a tested wireframe or prototype with real user feedback documented",
  },

  // Phase 5 — final tier of families, reaching 100% of families with a key
  "app-development": {
    displayName: "App Development",
    realTools: ["Flutter or React Native for cross-platform apps", "Xcode or Android Studio for native builds", "Git and an app store submission checklist"],
    coreWorkflow: "building and testing on a real device early, not just the simulator, before investing time in polish",
    commonPitfall: "testing only in the simulator or emulator and leaving real-device testing until the very end, when device-specific bugs surface",
    typicalOutput: "a working app installed and tested on a real device, ready for store submission or internal testing",
  },
  "remote-jobs": {
    displayName: "Remote Jobs",
    realTools: ["Remote-specific job boards such as We Work Remotely or Remote OK", "A portfolio tailored to proving async, self-managed output", "Video call tools for interviews, such as Zoom or Google Meet"],
    coreWorkflow: "targeting roles that are genuinely remote-first, with a portfolio proving async communication and self-management ability",
    commonPitfall: "applying to hybrid or office roles mislabeled as remote without checking the actual work-location requirement",
    typicalOutput: "applications to verified remote-first roles with a portfolio demonstrating asynchronous, self-directed work",
  },
  "social-media-marketing": {
    displayName: "Social Media Marketing",
    realTools: ["Native platform schedulers or tools like Buffer/Later", "Canva or CapCut for creative assets", "Native platform analytics for real engagement data"],
    coreWorkflow: "publishing consistently on one or two platforms with a content calendar, then reviewing real engagement data weekly",
    commonPitfall: "spreading effort across every platform at once instead of building consistency on the one or two that fit the audience",
    typicalOutput: "a content calendar with real engagement metrics tracked over several weeks",
  },
  "performance-marketing": {
    displayName: "Performance Marketing",
    realTools: ["Google Ads or Meta Ads Manager", "GA4 or a similar analytics setup for conversion tracking", "A/B testing on creative and targeting"],
    coreWorkflow: "running small, budget-capped tests, tracking cost-per-result precisely, and scaling only what's proven to work",
    commonPitfall: "scaling ad spend before a campaign has proven a stable, positive cost-per-result at small scale",
    typicalOutput: "a campaign with a proven, tracked cost-per-acquisition or cost-per-lead figure at a tested budget level",
  },
  "email-marketing": {
    displayName: "Email Marketing",
    realTools: ["An email platform such as Mailchimp or Klaviyo", "A segmented subscriber list", "A/B testing on subject lines and send times"],
    coreWorkflow: "building a segmented list and testing subject lines and content against real open and click-through rates",
    commonPitfall: "sending the same email to an entire unsegmented list regardless of subscriber interest or stage",
    typicalOutput: "a sent campaign or automated sequence with tracked open rates, click-through rates, and conversions",
  },
  "content-marketing": {
    displayName: "Content Marketing",
    realTools: ["A content calendar and topic-research process", "SEO or keyword tools where relevant, such as Ahrefs or Semrush", "Analytics to track real traffic and engagement per piece"],
    coreWorkflow: "publishing consistently around a defined topic cluster, then tracking which pieces actually drive traffic or leads",
    commonPitfall: "publishing one-off pieces on unrelated topics instead of building a connected content cluster that compounds authority",
    typicalOutput: "a published series of connected content pieces with tracked traffic and engagement data",
  },
  "youtube-growth": {
    displayName: "YouTube Growth",
    realTools: ["YouTube Studio analytics", "Video editing software such as Premiere Pro, CapCut, or DaVinci Resolve", "A thumbnail design tool such as Canva or Photoshop"],
    coreWorkflow: "publishing consistently, then using YouTube Studio's retention data to fix the specific point where viewers drop off",
    commonPitfall: "focusing only on view count while ignoring audience retention data, which is what actually drives the algorithm",
    typicalOutput: "a published video with tracked retention data used to improve the next one",
  },
  "instagram-growth": {
    displayName: "Instagram Growth",
    realTools: ["Instagram's native Insights analytics", "Canva or CapCut for content creation", "A content calendar for consistency"],
    coreWorkflow: "publishing consistently in one content format, then using native Insights to see what actually drives saves and shares",
    commonPitfall: "chasing follower count while ignoring saves and shares, which are stronger signals of content that's actually working",
    typicalOutput: "a content series with tracked saves, shares, and reach data used to refine the next pieces",
  },
  ecommerce: {
    displayName: "E-commerce",
    realTools: ["A storefront platform such as Shopify or WooCommerce", "A payment processor such as Razorpay, Stripe, or PayPal", "Analytics to track real conversion rate and cart abandonment"],
    coreWorkflow: "validating one product with real traffic and orders before expanding the catalog",
    commonPitfall: "listing a large catalog before validating demand for even one product with real orders",
    typicalOutput: "a live store with at least one product generating real, tracked sales",
  },
  "web-design": {
    displayName: "Web Design",
    realTools: ["Figma for design, Webflow or WordPress for the build", "A responsive design checklist covering mobile, tablet, and desktop", "Real user or client feedback before final handoff"],
    coreWorkflow: "designing mobile-first, then checking the design across real device sizes before development handoff",
    commonPitfall: "designing only for desktop and treating mobile as an afterthought, when most real traffic is often mobile",
    typicalOutput: "a finished, responsive design checked across real device sizes and ready for development",
  },
};

export function getFamilyFact(familyKey: string): FamilyFact | null {
  return FAMILY_FACTS[familyKey.trim().toLowerCase()] ?? null;
}
