import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const failures = [];

function read(file) {
  return fs.readFileSync(path.join(root, file), "utf8");
}

function assert(condition, message) {
  if (!condition) failures.push(message);
}

const middleware = read("middleware.ts");
const dashboardAuth = read("lib/dashboard-auth.ts");
const authLayout = read("app/auth/layout.tsx");
const adminLayout = read("app/admin/layout.tsx");
const adminDashboard = read("app/admin/dashboard/page.tsx");
const adminMasterclassDashboard = read("app/admin/masterclass-dashboard/page.tsx");
const adminTableApi = read("app/api/admin/table/route.ts");
const adminMetricsApi = read("app/api/admin/masterclass-metrics/route.ts");
const adminPushApi = read("app/api/admin/push/route.ts");
const adminPushControls = read("components/admin/AdminPushControls.tsx");
const loginRoute = read("app/api/dashboard-auth/login/route.ts");
const sitemapIndex = read("app/sitemap.xml/route.ts");
const htmlSitemap = read("app/site-map/page.tsx");
const robots = read("app/robots.ts");
const packageJson = JSON.parse(read("package.json"));

// P0: private pages and admin APIs require actual session auth, not robots.txt alone.
assert(middleware.includes('PRIVATE_PAGE_PREFIXES = ["/dashboard", "/admin"]'), "middleware must protect /dashboard and /admin pages");
assert(middleware.includes('PRIVATE_API_PREFIXES = ["/api/admin"]'), "middleware must protect /api/admin endpoints");
assert(middleware.includes("DASHBOARD_AUTH_COOKIE"), "middleware must validate the dashboard auth cookie");
assert(middleware.includes("isDashboardAuthValueValid"), "middleware dashboard session validation is missing");
assert(middleware.includes('"X-Robots-Tag"'), "private X-Robots-Tag is missing");
assert(dashboardAuth.includes("DASHBOARD_AUTH_TOKEN"), "central dashboard token validation is missing");
assert(adminLayout.includes("isDashboardAuthValueValid"), "admin server layout auth is missing");
assert(authLayout.includes("index: false"), "auth pages must remain noindex");
assert(loginRoute.includes("sanitizeDashboardNext"), "dashboard login must sanitize the post-login return target");
assert(loginRoute.includes("DASHBOARD_NEXT_COOKIE"), "dashboard login must preserve the requested private destination safely");

// Admin pages/APIs must not fall back to query-string ADMIN_TOKEN authentication.
const legacyAdminTokenFiles = [
  ["app/admin/dashboard/page.tsx", adminDashboard],
  ["app/admin/masterclass-dashboard/page.tsx", adminMasterclassDashboard],
  ["app/api/admin/table/route.ts", adminTableApi],
  ["app/api/admin/masterclass-metrics/route.ts", adminMetricsApi],
  ["app/api/admin/push/route.ts", adminPushApi],
  ["components/admin/AdminPushControls.tsx", adminPushControls],
];

for (const [file, text] of legacyAdminTokenFiles) {
  assert(!text.includes("ADMIN_TOKEN"), `${file} must not use legacy ADMIN_TOKEN auth`);
  assert(!text.includes("?token="), `${file} must not put admin tokens in URLs`);
  assert(!text.includes("searchParams?.token"), `${file} must not read admin tokens from page query params`);
}

assert(adminTableApi.includes("DASHBOARD_AUTH_COOKIE"), "admin table API must require dashboard session auth");
assert(adminMetricsApi.includes("DASHBOARD_AUTH_COOKIE"), "admin metrics API must require dashboard session auth");
assert(adminPushApi.includes("DASHBOARD_AUTH_COOKIE"), "admin push API must require dashboard session auth");

// P1/P3: unreviewed fully generated families must stay out of the sitemap index.
for (const risky of ["sitemap-expert", "sitemap-prompts", "sitemap-hindi", "sitemap-learn"]) {
  assert(!sitemapIndex.includes(risky), `${risky} must remain quarantined from sitemap.xml`);
}

// HTML sitemap must be curated, not generated by walking the application tree.
assert(!htmlSitemap.includes("collectRoutes("), "HTML sitemap must not recursively expose app routes");
assert(!htmlSitemap.includes('href: "/dashboard'), "HTML sitemap must not link dashboard routes");
assert(!htmlSitemap.includes('href: "/admin'), "HTML sitemap must not link admin routes");
assert(!htmlSitemap.includes('href: "/payment'), "HTML sitemap must not link payment-state routes");
assert(!htmlSitemap.includes('href: "/checkout'), "HTML sitemap must not link checkout-state routes");

// robots.txt is crawl guidance only; keep private route exclusions as an additional layer.
assert(robots.includes('"/dashboard/"'), "robots.txt dashboard exclusion is missing");
assert(robots.includes('"/admin/"'), "robots.txt admin exclusion is missing");
assert(robots.includes('sitemap: `${BASE}/sitemap.xml`'), "robots.txt sitemap declaration is missing");

// Catch the known duplicate-brand regression in source files without traversing generated data files.
const sourceRoots = ["app", "components", "lib"];
const duplicateBrand = /\|\s*Sikhadenge\s*\|\s*Sikhadenge/gi;
const sourceExtensions = new Set([".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"]);

function walk(dir) {
  if (!fs.existsSync(dir)) return;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (["node_modules", ".next", "_disabled_landing", "_disabled_meta_json_20260218_213242"].includes(entry.name)) continue;
      walk(full);
      continue;
    }
    if (!sourceExtensions.has(path.extname(entry.name))) continue;
    const relative = path.relative(root, full);
    const text = fs.readFileSync(full, "utf8");
    assert(!duplicateBrand.test(text), `duplicate Sikhadenge brand suffix found in ${relative}`);
    duplicateBrand.lastIndex = 0;
  }
}

for (const sourceRoot of sourceRoots) walk(path.join(root, sourceRoot));

// Bulk publishing commands must remain guard-wrapped.
const guardedScripts = [
  "seo:generate",
  "seo:refresh",
  "seo:expand",
  "blog:prepare-10k",
  "blog:prepare-100k",
  "blog:apply-phase",
  "blog:apply-phase-1",
  "blog:apply-phase-2",
];

for (const script of guardedScripts) {
  const command = packageJson.scripts?.[script] || "";
  assert(command.includes("seo-guard.mjs"), `${script} must run the SEO guard before publishing/generation`);
}

assert(packageJson.scripts?.["blog:classify"]?.includes("classify-blog-inventory.mjs"), "blog:classify audit command is missing");

if (failures.length) {
  console.error("SEO GUARD: FAIL");
  for (const failure of failures) console.error(`- ${failure}`);
  process.exit(1);
}

console.log("SEO GUARD: PASS");
