import Link from "next/link";
import Image from "next/image";
import Script from "next/script";
import { prisma } from "@/lib/prisma"; export const dynamic = "force-dynamic";
export const revalidate = 0; export const metadata = { title: "Masterclass Registration | Sikhadenge", description: "Register for the Sikhadenge masterclass and get your Zoom access after submission.",
}; type PageProps = { searchParams?: { ok?: string; phone?: string; };
}; function SuccessCard({ phone, zoomLink }: { phone?: string; zoomLink: string }) { return ( <div className="overflow-hidden rounded-[30px] border border-slate-200 bg-white shadow-[0_20px_60px_rgba(15,23,42,0.10)]"><div className="bg-[#08152f] px-6 py-6 text-center sm:px-8"><div className="mx-auto flex h-[58px] w-[190px] items-center justify-center rounded-2xl bg-white px-4 py-2 shadow-sm">
<Image
src="/brand/sikhadenge-header-safe-320.png?v=headersafe2-20260728"
alt="Sikhadenge"
width={170}
height={46}
priority
className="max-h-[42px] w-auto object-contain"
/>
</div><p className="mt-3 text-[11px] font-semibold uppercase tracking-[0.20em] text-blue-100"> Sikhadenge Masterclass Access </p></div><div className="p-6 sm:p-8"><h1 className="text-center text-[34px] font-bold tracking-tight text-slate-900 sm:text-[42px]"> Registration successful </h1><p className="mx-auto mt-4 max-w-lg text-center text-sm leading-7 text-slate-600 sm:text-base"> Your Zoom access is ready. You will be redirected automatically in 2 seconds. </p> {phone ? ( <div className="mt-6 rounded-[22px] border border-emerald-200 bg-emerald-50 px-5 py-4 text-base text-slate-700"> Registered phone: <span className="font-semibold text-slate-900">{phone}</span></div> ) : null} <div className="mt-5 rounded-[22px] bg-emerald-50 px-5 py-4 text-base text-emerald-800"> Zoom link is enabled for your registration. </div><div className="mt-7 flex flex-col gap-4"><a href={zoomLink} target="_blank" rel="noopener noreferrer" className="inline-flex h-14 items-center justify-center rounded-[22px] bg-blue-600 px-5 text-base font-semibold text-white transition hover:bg-blue-700" > Join Zoom Now </a><Link href="/" className="inline-flex h-14 items-center justify-center rounded-[22px] border border-slate-200 bg-white px-5 text-base font-semibold text-slate-700 transition hover:bg-slate-50" > Back to Home </Link></div></div></div> );
} function FormCard() { return ( <div className="overflow-hidden rounded-[30px] border border-slate-200 bg-white shadow-[0_20px_60px_rgba(15,23,42,0.10)]"><div className="bg-[#08152f] px-6 py-6 text-center sm:px-8"><div className="mx-auto flex h-[58px] w-[190px] items-center justify-center rounded-2xl bg-white px-4 py-2 shadow-sm">
<Image
src="/brand/sikhadenge-header-safe-320.png?v=headersafe2-20260728"
alt="Sikhadenge"
width={170}
height={46}
priority
className="max-h-[42px] w-auto object-contain"
/>
</div><p className="mt-3 text-[11px] font-semibold uppercase tracking-[0.20em] text-blue-100"> Sikhadenge Masterclass Registration </p></div><div className="p-6 sm:p-8"><h1 className="text-center text-2xl font-bold tracking-tight text-slate-900 sm:text-3xl"> Register Your Seat </h1><p className="mt-3 text-center text-sm leading-6 text-slate-600"> Fill your details below to join the live masterclass instantly. </p><form action="/api/masterclass" method="post" className="mt-7 space-y-5"><input type="hidden" name="page" value="/masterclass" /><div><label htmlFor="name" className="mb-2 block text-sm font-semibold text-slate-900"> Full Name <span className="text-rose-500">*</span></label><input id="name" name="name" type="text" required placeholder="Enter your full name" className="h-12 w-full rounded-[18px] border border-slate-300 bg-white px-4 text-sm text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-blue-500 focus:ring-4 focus:ring-blue-100" /></div><div><label htmlFor="email" className="mb-2 block text-sm font-semibold text-slate-900"> Email Address <span className="text-rose-500">*</span></label><input id="email" name="email" type="email" required placeholder="Enter your email" className="h-12 w-full rounded-[18px] border border-slate-300 bg-white px-4 text-sm text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-blue-500 focus:ring-4 focus:ring-blue-100" /></div><div><label htmlFor="phone" className="mb-2 block text-sm font-semibold text-slate-900"> Mobile Number (WhatsApp Number) <span className="text-rose-500">*</span></label><div className="flex overflow-hidden rounded-[18px] border border-slate-300 bg-white focus-within:border-blue-500 focus-within:ring-4 focus-within:ring-blue-100"><div className="flex h-12 min-w-[72px] items-center justify-center border-r border-slate-200 bg-slate-50 text-sm font-semibold text-slate-700"> +91 </div><input id="phone" name="phone" type="tel" inputMode="numeric" required maxLength={10} minLength={10} pattern="[6-9][0-9]{9}" title="Enter a valid 10-digit Indian mobile number" placeholder="Enter your WhatsApp number" className="h-12 w-full px-4 text-sm text-slate-900 outline-none placeholder:text-slate-400" /></div></div><p className="text-xs leading-5 text-slate-500"> Enter a valid 10-digit Indian WhatsApp number starting with 6, 7, 8, or 9. </p><button type="submit" className="inline-flex h-12 w-full items-center justify-center rounded-[18px] bg-blue-600 px-5 text-sm font-semibold text-white shadow-sm transition hover:bg-blue-700" > Submit and Join </button></form></div></div> );
} export default async function MasterclassPage({ searchParams }: PageProps) { const ok = searchParams?.ok === "1"; const phone = searchParams?.phone ?? ""; const zoomSetting = await prisma.siteSetting.findUnique({ where: { key: "masterclass_zoom_url" }, }); const zoomLink = zoomSetting?.value?.trim() || process.env.NEXT_PUBLIC_MASTERCLASS_ZOOM_URL || "https://zoom.us/j/"; return ( <> {ok ? ( <Script id="masterclass-success-redirect" strategy="afterInteractive"> {`setTimeout(function () { window.location.href = "${zoomLink}"; }, 2000);`} </Script> ) : null} <main className="-mt-16 min-h-[100dvh] bg-[#f8fafc] text-slate-900 sm:-mt-[60px] flex items-center"><section className="relative w-full overflow-hidden"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top_left,rgba(37,99,235,0.10),transparent_28%),radial-gradient(circle_at_bottom_right,rgba(15,23,42,0.05),transparent_24%)]" /><div className="relative mx-auto max-w-xl px-4 py-2 sm:px-6 sm:py-2 lg:px-8"> {ok ? <SuccessCard phone={phone} zoomLink={zoomLink} /> : <FormCard />} </div></section></main></> );
}
